// Datos reales de LaLiga 2025/2026 extraídos de Wikipedia + FotMob
// Fuente: https://en.wikipedia.org/wiki/2025%E2%80%9326_La_Liga
// Fuente: https://www.fotmob.com/es/leagues/87/overview/laliga

export interface LigaTeamData {
  name: string;
  shortName: string;
  country: string;
  colors: { primary: string; secondary: string; accent: string };
  players: LigaPlayerData[];
}

export interface LigaPlayerData {
  name: string;
  position: "GK" | "DEF" | "MID" | "FWD";
  attack: number;
  control: number;
  defense: number;
  total: number;
  rarity: "BASE" | "RARE" | "EPIC" | "LEGENDARY" | "GOLDEN" | "MOMENTUM" | "ULTRA_RARE";
  goals?: number;
  assists?: number;
  rating?: number;
}

const R = (a: number, c: number, d: number) => ({
  attack: a, control: c, defense: d, total: Math.round((a + c + d) / 3)
});

export const LIGA_TEAMS: LigaTeamData[] = [
  {
    name: "Barcelona", shortName: "BAR", country: "España",
    colors: { primary: "#a50044", secondary: "#004d98", accent: "#ffcc00" },
    players: [
      { name: "Joan García", position: "GK", ...R(30, 65, 92), rarity: "LEGENDARY", rating: 7.5 },
      { name: "Pau Cubarsí", position: "DEF", ...R(45, 70, 90), rarity: "EPIC", rating: 7.4 },
      { name: "Ronald Araújo", position: "DEF", ...R(50, 72, 92), rarity: "LEGENDARY", rating: 7.5 },
      { name: "Eric García", position: "DEF", ...R(55, 78, 88), rarity: "RARE", rating: 7.2 },
      { name: "Alejandro Balde", position: "DEF", ...R(65, 75, 82), rarity: "EPIC", rating: 7.3 },
      { name: "Jules Koundé", position: "DEF", ...R(55, 74, 86), rarity: "RARE", rating: 7.1 },
      { name: "Pedri", position: "MID", ...R(72, 92, 68), rarity: "LEGENDARY", goals: 10, assists: 8, rating: 7.8 },
      { name: "Fermín López", position: "MID", ...R(78, 85, 60), rarity: "EPIC", goals: 12, assists: 6, rating: 7.5 },
      { name: "Gavi", position: "MID", ...R(65, 88, 65), rarity: "EPIC", rating: 7.3 },
      { name: "Dani Olmo", position: "MID", ...R(80, 85, 55), rarity: "EPIC", goals: 8, assists: 7, rating: 7.4 },
      { name: "Lamine Yamal", position: "FWD", ...R(90, 85, 35), rarity: "ULTRA_RARE", goals: 16, assists: 11, rating: 8.33 },
      { name: "Ferran Torres", position: "FWD", ...R(85, 72, 40), rarity: "GOLDEN", goals: 16, assists: 5, rating: 7.5 },
      { name: "Robert Lewandowski", position: "FWD", ...R(88, 70, 30), rarity: "LEGENDARY", goals: 14, assists: 4, rating: 7.3 },
      { name: "Raphinha", position: "FWD", ...R(82, 75, 35), rarity: "EPIC", goals: 8, assists: 6, rating: 7.2 },
      { name: "Frenkie de Jong", position: "MID", ...R(68, 88, 72), rarity: "LEGENDARY", rating: 7.4 },
      { name: "Andreas Christensen", position: "DEF", ...R(40, 70, 85), rarity: "RARE", rating: 7.0 },
    ],
  },
  {
    name: "Real Madrid", shortName: "RMA", country: "España",
    colors: { primary: "#ffffff", secondary: "#085098", accent: "#febd11" },
    players: [
      { name: "Thibaut Courtois", position: "GK", ...R(25, 60, 95), rarity: "LEGENDARY", rating: 7.6 },
      { name: "Antonio Rüdiger", position: "DEF", ...R(50, 68, 90), rarity: "EPIC", rating: 7.3 },
      { name: "Éder Militão", position: "DEF", ...R(45, 72, 88), rarity: "EPIC", rating: 7.2 },
      { name: "David Alaba", position: "DEF", ...R(60, 82, 85), rarity: "LEGENDARY", rating: 7.4 },
      { name: "Dani Carvajal", position: "DEF", ...R(60, 72, 84), rarity: "EPIC", rating: 7.1 },
      { name: "Ferland Mendy", position: "DEF", ...R(50, 70, 82), rarity: "RARE", rating: 7.0 },
      { name: "Eduardo Camavinga", position: "MID", ...R(65, 85, 72), rarity: "EPIC", rating: 7.3 },
      { name: "Federico Valverde", position: "MID", ...R(78, 82, 68), rarity: "LEGENDARY", goals: 7, assists: 5, rating: 7.5 },
      { name: "Aurélien Tchouaméni", position: "MID", ...R(55, 80, 78), rarity: "EPIC", rating: 7.2 },
      { name: "Jude Bellingham", position: "MID", ...R(85, 82, 65), rarity: "LEGENDARY", goals: 11, assists: 7, rating: 7.6 },
      { name: "Arda Güler", position: "MID", ...R(80, 88, 40), rarity: "GOLDEN", goals: 9, assists: 9, rating: 7.7 },
      { name: "Kylian Mbappé", position: "FWD", ...R(97, 85, 30), rarity: "ULTRA_RARE", goals: 25, assists: 6, rating: 8.02 },
      { name: "Vinícius Júnior", position: "FWD", ...R(92, 78, 30), rarity: "GOLDEN", goals: 16, assists: 8, rating: 7.8 },
      { name: "Rodrygo", position: "FWD", ...R(82, 80, 35), rarity: "EPIC", goals: 7, assists: 6, rating: 7.2 },
      { name: "Endrick", position: "FWD", ...R(78, 65, 20), rarity: "RARE", rating: 6.9 },
      { name: "Brahim Díaz", position: "MID", ...R(75, 78, 35), rarity: "RARE", rating: 7.0 },
    ],
  },
  {
    name: "Villarreal", shortName: "VIL", country: "España",
    colors: { primary: "#ffcc00", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Luiz Júnior", position: "GK", ...R(30, 62, 88), rarity: "RARE", rating: 7.1 },
      { name: "Santiago Mouriño", position: "DEF", ...R(50, 72, 86), rarity: "EPIC", rating: 7.4 },
      { name: "Raúl Albiol", position: "DEF", ...R(40, 70, 85), rarity: "RARE", rating: 7.0 },
      { name: "Juan Foyth", position: "DEF", ...R(55, 72, 84), rarity: "RARE", rating: 7.1 },
      { name: "Álex Baena", position: "MID", ...R(82, 85, 40), rarity: "EPIC", goals: 8, assists: 8, rating: 7.5 },
      { name: "Dani Parejo", position: "MID", ...R(60, 88, 55), rarity: "RARE", rating: 7.2 },
      { name: "Étienne Capoue", position: "MID", ...R(55, 75, 72), rarity: "RARE", rating: 7.0 },
      { name: "Alberto Moleiro", position: "MID", ...R(75, 82, 40), rarity: "EPIC", rating: 7.3 },
      { name: "Nicolas Pépé", position: "FWD", ...R(82, 72, 30), rarity: "EPIC", goals: 10, assists: 5, rating: 7.4 },
      { name: "Gerard Moreno", position: "FWD", ...R(80, 72, 35), rarity: "EPIC", goals: 9, assists: 5, rating: 7.2 },
      { name: "Thierno Barry", position: "FWD", ...R(78, 60, 30), rarity: "RARE", goals: 12, assists: 3, rating: 7.1 },
      { name: "Pape Gueye", position: "MID", ...R(60, 75, 70), rarity: "RARE", rating: 7.0 },
      { name: "Juan Bernat", position: "DEF", ...R(55, 72, 78), rarity: "RARE", rating: 6.9 },
      { name: "Sergi Cardona", position: "DEF", ...R(55, 70, 78), rarity: "BASE", rating: 6.8 },
      { name: "Tajon Buchanan", position: "FWD", ...R(75, 68, 30), rarity: "RARE", rating: 7.0 },
      { name: "Kiko Femenía", position: "DEF", ...R(50, 68, 76), rarity: "BASE", rating: 6.8 },
    ],
  },
  {
    name: "Atlético Madrid", shortName: "ATM", country: "España",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Jan Oblak", position: "GK", ...R(25, 55, 93), rarity: "LEGENDARY", rating: 7.5 },
      { name: "Marc Pubill", position: "DEF", ...R(60, 72, 85), rarity: "EPIC", rating: 7.3 },
      { name: "José María Giménez", position: "DEF", ...R(40, 65, 88), rarity: "EPIC", rating: 7.2 },
      { name: "Marcos Llorente", position: "DEF", ...R(72, 78, 80), rarity: "EPIC", rating: 7.3 },
      { name: "Reinildo", position: "DEF", ...R(45, 68, 82), rarity: "RARE", rating: 7.0 },
      { name: "Nahuel Molina", position: "DEF", ...R(65, 72, 78), rarity: "RARE", rating: 7.0 },
      { name: "Rodrigo De Paul", position: "MID", ...R(72, 82, 60), rarity: "EPIC", rating: 7.3 },
      { name: "Koke", position: "MID", ...R(55, 85, 62), rarity: "RARE", rating: 7.1 },
      { name: "Pablo Barrios", position: "MID", ...R(65, 80, 58), rarity: "RARE", rating: 7.1 },
      { name: "Julián Alvarez", position: "FWD", ...R(88, 78, 35), rarity: "GOLDEN", goals: 13, assists: 7, rating: 7.6 },
      { name: "Antoine Griezmann", position: "FWD", ...R(85, 82, 40), rarity: "LEGENDARY", goals: 11, assists: 6, rating: 7.5 },
      { name: "Ángel Correa", position: "FWD", ...R(78, 72, 30), rarity: "RARE", goals: 6, assists: 5, rating: 7.1 },
      { name: "Alexander Sørloth", position: "FWD", ...R(80, 60, 25), rarity: "RARE", goals: 7, assists: 3, rating: 6.9 },
      { name: "Arthur Vermeeren", position: "MID", ...R(55, 75, 55), rarity: "RARE", rating: 6.9 },
      { name: "César Azpilicueta", position: "DEF", ...R(40, 68, 80), rarity: "BASE", rating: 6.8 },
      { name: "Javi Galán", position: "DEF", ...R(50, 70, 78), rarity: "BASE", rating: 6.7 },
    ],
  },
  {
    name: "Real Betis", shortName: "BET", country: "España",
    colors: { primary: "#009a44", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Adrián San Miguel", position: "GK", ...R(30, 60, 85), rarity: "RARE", rating: 7.0 },
      { name: "Marc Bartra", position: "DEF", ...R(45, 70, 84), rarity: "RARE", rating: 7.0 },
      { name: "Diego Llorente", position: "DEF", ...R(45, 68, 82), rarity: "RARE", rating: 6.9 },
      { name: "Aitor Ruibal", position: "DEF", ...R(60, 70, 78), rarity: "RARE", rating: 7.0 },
      { name: "Juan Miranda", position: "DEF", ...R(55, 72, 78), rarity: "RARE", rating: 6.9 },
      { name: "William Carvalho", position: "MID", ...R(60, 82, 60), rarity: "RARE", rating: 7.0 },
      { name: "Marc Roca", position: "MID", ...R(50, 78, 65), rarity: "RARE", rating: 6.9 },
      { name: "Isco", position: "MID", ...R(72, 88, 45), rarity: "EPIC", goals: 6, assists: 6, rating: 7.3 },
      { name: "Sergi Altimira", position: "MID", ...R(55, 75, 55), rarity: "BASE", rating: 6.8 },
      { name: "Nabil Fekir", position: "MID", ...R(80, 82, 35), rarity: "EPIC", rating: 7.2 },
      { name: "Chimy Ávila", position: "FWD", ...R(80, 65, 30), rarity: "RARE", goals: 7, assists: 4, rating: 7.0 },
      { name: "Borja Iglesias", position: "FWD", ...R(78, 65, 25), rarity: "RARE", goals: 6, assists: 3, rating: 6.9 },
      { name: "Vitor Roque", position: "FWD", ...R(76, 68, 25), rarity: "RARE", rating: 6.9 },
      { name: "Assane Diao", position: "FWD", ...R(72, 65, 25), rarity: "BASE", rating: 6.8 },
      { name: "Johnny Cardoso", position: "MID", ...R(55, 75, 60), rarity: "RARE", rating: 6.9 },
      { name: "Romain Perraud", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
    ],
  },
  {
    name: "Celta Vigo", shortName: "CEL", country: "España",
    colors: { primary: "#75aadb", secondary: "#ffffff", accent: "#c8102e" },
    players: [
      { name: "Vicente Guaita", position: "GK", ...R(25, 58, 84), rarity: "RARE", rating: 7.0 },
      { name: "Carlos Domínguez", position: "DEF", ...R(40, 65, 80), rarity: "BASE", rating: 6.8 },
      { name: "Joseph Aidoo", position: "DEF", ...R(35, 62, 82), rarity: "RARE", rating: 6.9 },
      { name: "Javier Manquillo", position: "DEF", ...R(50, 65, 78), rarity: "BASE", rating: 6.7 },
      { name: "Mihailo Ristić", position: "DEF", ...R(50, 68, 76), rarity: "BASE", rating: 6.7 },
      { name: "Fran Beltran", position: "MID", ...R(55, 78, 55), rarity: "RARE", rating: 7.0 },
      { name: "Iago Aspas", position: "FWD", ...R(85, 78, 30), rarity: "EPIC", goals: 10, assists: 6, rating: 7.4 },
      { name: "Jørgen Strand Larsen", position: "FWD", ...R(80, 65, 28), rarity: "RARE", goals: 7, assists: 4, rating: 7.0 },
      { name: "Williot Swedberg", position: "MID", ...R(68, 72, 35), rarity: "RARE", rating: 6.9 },
      { name: "Luca de la Torre", position: "MID", ...R(60, 75, 50), rarity: "BASE", rating: 6.8 },
      { name: "Anastasios Douvikas", position: "FWD", ...R(76, 62, 25), rarity: "RARE", rating: 6.9 },
      { name: "Hugo Sotelo", position: "MID", ...R(55, 72, 50), rarity: "BASE", rating: 6.7 },
      { name: "Óscar Mingueza", position: "DEF", ...R(55, 68, 78), rarity: "RARE", rating: 6.9 },
      { name: "Carles Pérez", position: "FWD", ...R(72, 68, 30), rarity: "BASE", rating: 6.8 },
      { name: "Unai Núñez", position: "DEF", ...R(35, 62, 80), rarity: "BASE", rating: 6.7 },
      { name: "Marcos Alonso", position: "DEF", ...R(55, 72, 76), rarity: "RARE", rating: 6.9 },
    ],
  },
  {
    name: "Getafe", shortName: "GET", country: "España",
    colors: { primary: "#005dbb", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "David Soria", position: "GK", ...R(25, 58, 88), rarity: "EPIC", rating: 7.2 },
      { name: "Domingos Duarte", position: "DEF", ...R(35, 62, 82), rarity: "RARE", rating: 6.9 },
      { name: "Djené", position: "DEF", ...R(30, 58, 85), rarity: "RARE", rating: 7.0 },
      { name: "Gastón Álvarez", position: "DEF", ...R(45, 65, 80), rarity: "BASE", rating: 6.8 },
      { name: "Juan Iglesias", position: "DEF", ...R(50, 65, 78), rarity: "BASE", rating: 6.7 },
      { name: "Luis Milla", position: "MID", ...R(65, 82, 55), rarity: "EPIC", goals: 4, assists: 10, rating: 7.4 },
      { name: "Carles Aleñá", position: "MID", ...R(60, 80, 50), rarity: "RARE", rating: 7.0 },
      { name: "Mauro Arambarri", position: "MID", ...R(55, 72, 65), rarity: "RARE", rating: 6.9 },
      { name: "Aleñá", position: "MID", ...R(60, 78, 50), rarity: "RARE", rating: 7.0 },
      { name: "Borja Mayoral", position: "FWD", ...R(78, 65, 28), rarity: "EPIC", goals: 8, assists: 3, rating: 7.1 },
      { name: "Mason Greenwood", position: "FWD", ...R(80, 72, 30), rarity: "EPIC", goals: 6, assists: 4, rating: 7.2 },
      { name: "Chidera Ejuke", position: "FWD", ...R(75, 68, 25), rarity: "RARE", rating: 6.9 },
      { name: "Peter González", position: "FWD", ...R(70, 65, 25), rarity: "BASE", rating: 6.8 },
      { name: "Oscar Rodríguez", position: "MID", ...R(72, 75, 40), rarity: "RARE", rating: 7.0 },
      { name: "Adrián Liso", position: "MID", ...R(65, 72, 35), rarity: "RARE", rating: 6.9 },
      { name: "Nemanja Maksimović", position: "MID", ...R(50, 72, 65), rarity: "BASE", rating: 6.8 },
    ],
  },
  {
    name: "Rayo Vallecano", shortName: "RAY", country: "España",
    colors: { primary: "#da291c", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Augusto Batalla", position: "GK", ...R(30, 58, 82), rarity: "RARE", rating: 6.9 },
      { name: "Iván Balliu", position: "DEF", ...R(50, 65, 78), rarity: "BASE", rating: 6.8 },
      { name: "Abdul Mumin", position: "DEF", ...R(35, 60, 80), rarity: "BASE", rating: 6.7 },
      { name: "Florian Lejeune", position: "DEF", ...R(45, 68, 82), rarity: "RARE", rating: 6.9 },
      { name: "Pep Chavarría", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Pathé Ciss", position: "MID", ...R(55, 72, 65), rarity: "RARE", rating: 6.9 },
      { name: "Óscar Valentín", position: "MID", ...R(50, 75, 60), rarity: "BASE", rating: 6.8 },
      { name: "Isi Palazón", position: "MID", ...R(78, 76, 35), rarity: "EPIC", goals: 7, assists: 5, rating: 7.2 },
      { name: "Álvaro García", position: "FWD", ...R(76, 70, 30), rarity: "RARE", goals: 5, assists: 5, rating: 7.0 },
      { name: "Sergio Camello", position: "FWD", ...R(72, 65, 28), rarity: "RARE", rating: 6.9 },
      { name: "Randy Nteka", position: "FWD", ...R(70, 68, 25), rarity: "BASE", rating: 6.8 },
      { name: "De Frutos", position: "FWD", ...R(72, 68, 28), rarity: "RARE", rating: 6.9 },
      { name: "Unai López", position: "MID", ...R(58, 75, 52), rarity: "BASE", rating: 6.8 },
      { name: "Aridane Hernández", position: "DEF", ...R(35, 60, 80), rarity: "BASE", rating: 6.7 },
      { name: "Raúl de Tomás", position: "FWD", ...R(76, 65, 25), rarity: "RARE", rating: 6.9 },
      { name: "Kike Pérez", position: "MID", ...R(55, 72, 55), rarity: "BASE", rating: 6.7 },
    ],
  },
  {
    name: "Valencia", shortName: "VAL", country: "España",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Giorgi Mamardashvili", position: "GK", ...R(30, 60, 88), rarity: "EPIC", rating: 7.2 },
      { name: "Cristhian Mosquera", position: "DEF", ...R(40, 65, 82), rarity: "RARE", rating: 7.0 },
      { name: "Mouctar Diakhaby", position: "DEF", ...R(35, 60, 80), rarity: "RARE", rating: 6.9 },
      { name: "Yarek Gąsiorowski", position: "DEF", ...R(40, 62, 78), rarity: "BASE", rating: 6.7 },
      { name: "Jesús Vázquez", position: "DEF", ...R(50, 66, 76), rarity: "BASE", rating: 6.7 },
      { name: "Pepelu", position: "MID", ...R(50, 78, 62), rarity: "RARE", rating: 7.0 },
      { name: "Javi Guerra", position: "MID", ...R(65, 76, 55), rarity: "RARE", rating: 7.0 },
      { name: "André Almeida", position: "MID", ...R(68, 75, 48), rarity: "RARE", rating: 6.9 },
      { name: "Diego López", position: "FWD", ...R(72, 68, 28), rarity: "RARE", goals: 6, assists: 4, rating: 7.0 },
      { name: "Hugo Duro", position: "FWD", ...R(76, 65, 30), rarity: "EPIC", goals: 9, assists: 3, rating: 7.1 },
      { name: "Federico Viñas", position: "FWD", ...R(74, 62, 28), rarity: "RARE", rating: 6.9 },
      { name: "Sergi Canós", position: "FWD", ...R(72, 68, 30), rarity: "RARE", rating: 6.9 },
      { name: "Fran Pérez", position: "FWD", ...R(70, 65, 25), rarity: "BASE", rating: 6.7 },
      { name: "Luis Rioja", position: "FWD", ...R(72, 68, 30), rarity: "RARE", rating: 6.9 },
      { name: "Hugo Guillamón", position: "DEF", ...R(45, 72, 78), rarity: "RARE", rating: 6.9 },
      { name: "José Gayà", position: "DEF", ...R(60, 76, 82), rarity: "EPIC", rating: 7.2 },
    ],
  },
  {
    name: "Real Sociedad", shortName: "RSO", country: "España",
    colors: { primary: "#ffffff", secondary: "#005dbb", accent: "#000000" },
    players: [
      { name: "Álex Remiro", position: "GK", ...R(28, 60, 86), rarity: "EPIC", rating: 7.1 },
      { name: "Robin Le Normand", position: "DEF", ...R(40, 68, 86), rarity: "EPIC", rating: 7.2 },
      { name: "Igor Zubeldia", position: "DEF", ...R(35, 65, 82), rarity: "RARE", rating: 7.0 },
      { name: "Hamari Traoré", position: "DEF", ...R(55, 68, 80), rarity: "RARE", rating: 6.9 },
      { name: "Javi Galán", position: "DEF", ...R(50, 70, 78), rarity: "BASE", rating: 6.8 },
      { name: "Martín Zubimendi", position: "MID", ...R(55, 85, 68), rarity: "LEGENDARY", rating: 7.5 },
      { name: "Mikel Merino", position: "MID", ...R(72, 80, 62), rarity: "EPIC", goals: 6, assists: 5, rating: 7.3 },
      { name: "Brais Méndez", position: "MID", ...R(76, 80, 45), rarity: "EPIC", goals: 5, assists: 6, rating: 7.2 },
      { name: "Takefusa Kubo", position: "FWD", ...R(82, 78, 30), rarity: "EPIC", goals: 7, assists: 5, rating: 7.3 },
      { name: "Mikel Oyarzabal", position: "FWD", ...R(84, 78, 35), rarity: "GOLDEN", goals: 15, assists: 5, rating: 7.5 },
      { name: "Sheraldo Becker", position: "FWD", ...R(78, 65, 25), rarity: "RARE", goals: 6, assists: 3, rating: 7.0 },
      { name: "Ander Barrenetxea", position: "FWD", ...R(74, 72, 28), rarity: "RARE", rating: 6.9 },
      { name: "Jon Martín", position: "DEF", ...R(40, 60, 78), rarity: "BASE", rating: 6.7 },
      { name: "Beñat Turrientes", position: "MID", ...R(55, 76, 52), rarity: "RARE", rating: 6.9 },
      { name: "Arsen Zakharyan", position: "MID", ...R(68, 75, 40), rarity: "RARE", rating: 6.9 },
      { name: "Carlos Fernández", position: "FWD", ...R(72, 65, 25), rarity: "BASE", rating: 6.8 },
    ],
  },
  {
    name: "Espanyol", shortName: "ESP", country: "España",
    colors: { primary: "#005dbb", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Antonio Sivera", position: "GK", ...R(28, 58, 84), rarity: "RARE", rating: 7.0 },
      { name: "Fernando Calero", position: "DEF", ...R(35, 62, 80), rarity: "BASE", rating: 6.8 },
      { name: "Carlos Romero", position: "DEF", ...R(55, 68, 80), rarity: "EPIC", rating: 7.1 },
      { name: "Brian Olivan", position: "DEF", ...R(50, 65, 78), rarity: "BASE", rating: 6.7 },
      { name: "Omar El Hilali", position: "DEF", ...R(50, 62, 76), rarity: "BASE", rating: 6.7 },
      { name: "Álvaro Aguado", position: "MID", ...R(55, 75, 48), rarity: "BASE", rating: 6.8 },
      { name: "Edu Expósito", position: "MID", ...R(60, 78, 50), rarity: "RARE", rating: 6.9 },
      { name: "José Gragera", position: "MID", ...R(50, 72, 58), rarity: "BASE", rating: 6.7 },
      { name: "Jofre Carreras", position: "FWD", ...R(70, 68, 28), rarity: "RARE", rating: 6.9 },
      { name: "Martin Braithwaite", position: "FWD", ...R(76, 65, 28), rarity: "RARE", goals: 8, assists: 3, rating: 7.1 },
      { name: "Keita Baldé", position: "FWD", ...R(74, 68, 25), rarity: "RARE", rating: 6.9 },
      { name: "Javi Puado", position: "FWD", ...R(72, 68, 30), rarity: "RARE", goals: 6, assists: 4, rating: 7.0 },
      { name: "Álvaro Tejero", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Nico Melamed", position: "MID", ...R(65, 74, 38), rarity: "RARE", rating: 6.9 },
      { name: "Pere Milla", position: "FWD", ...R(70, 65, 28), rarity: "BASE", rating: 6.8 },
      { name: "Alejandro Rego", position: "GK", ...R(25, 55, 80), rarity: "BASE", rating: 6.7 },
    ],
  },
  {
    name: "Athletic Bilbao", shortName: "ATH", country: "España",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Unai Simón", position: "GK", ...R(30, 62, 90), rarity: "LEGENDARY", rating: 7.4 },
      { name: "Dani Vivian", position: "DEF", ...R(45, 68, 86), rarity: "EPIC", rating: 7.2 },
      { name: "Aitor Paredes", position: "DEF", ...R(40, 62, 82), rarity: "RARE", rating: 7.0 },
      { name: "Yeray Álvarez", position: "DEF", ...R(35, 65, 84), rarity: "EPIC", rating: 7.1 },
      { name: "Óscar de Marcos", position: "DEF", ...R(55, 72, 78), rarity: "RARE", rating: 6.9 },
      { name: "Dani García", position: "MID", ...R(45, 75, 65), rarity: "RARE", rating: 7.0 },
      { name: "Beñat Prados", position: "MID", ...R(55, 76, 58), rarity: "RARE", rating: 7.0 },
      { name: "Oihan Sancet", position: "MID", ...R(76, 80, 48), rarity: "EPIC", goals: 5, assists: 5, rating: 7.2 },
      { name: "Nico Williams", position: "FWD", ...R(86, 76, 30), rarity: "GOLDEN", goals: 7, assists: 6, rating: 7.4 },
      { name: "Iñaki Williams", position: "FWD", ...R(82, 72, 32), rarity: "EPIC", goals: 8, assists: 4, rating: 7.2 },
      { name: "Gorka Guruzeta", position: "FWD", ...R(74, 65, 28), rarity: "RARE", goals: 6, assists: 3, rating: 7.0 },
      { name: "Álex Berenguer", position: "FWD", ...R(72, 70, 30), rarity: "RARE", rating: 6.9 },
      { name: "Mikel Vesga", position: "MID", ...R(50, 75, 60), rarity: "RARE", rating: 6.9 },
      { name: "Julen Agirrezabala", position: "GK", ...R(25, 58, 84), rarity: "RARE", rating: 6.9 },
      { name: "Unai Gómez", position: "MID", ...R(62, 72, 42), rarity: "RARE", rating: 6.8 },
      { name: "Yuri Berchiche", position: "DEF", ...R(50, 72, 78), rarity: "RARE", rating: 6.9 },
    ],
  },
  {
    name: "Sevilla", shortName: "SEV", country: "España",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Orjan Nyland", position: "GK", ...R(28, 58, 82), rarity: "RARE", rating: 6.9 },
      { name: "Loïc Badé", position: "DEF", ...R(40, 65, 84), rarity: "EPIC", rating: 7.1 },
      { name: "Kike Salas", position: "DEF", ...R(35, 62, 80), rarity: "RARE", rating: 6.9 },
      { name: "Marcos Acuña", position: "DEF", ...R(60, 72, 78), rarity: "RARE", rating: 7.0 },
      { name: "José Ángel Carmona", position: "DEF", ...R(55, 66, 78), rarity: "BASE", rating: 6.8 },
      { name: "Nemanja Gudelj", position: "MID", ...R(50, 72, 65), rarity: "RARE", rating: 6.9 },
      { name: "Albert Sambi Lokonga", position: "MID", ...R(55, 76, 58), rarity: "RARE", rating: 6.9 },
      { name: "Lucien Agoumé", position: "MID", ...R(55, 72, 52), rarity: "BASE", rating: 6.7 },
      { name: "Suso", position: "MID", ...R(72, 80, 35), rarity: "RARE", rating: 7.1 },
      { name: "Dodi Lukebakio", position: "FWD", ...R(80, 70, 28), rarity: "EPIC", goals: 7, assists: 4, rating: 7.2 },
      { name: "Isaac Romero", position: "FWD", ...R(74, 65, 28), rarity: "RARE", goals: 6, assists: 3, rating: 7.0 },
      { name: "Juanlu Sánchez", position: "MID", ...R(65, 72, 48), rarity: "RARE", rating: 6.9 },
      { name: "Chidera Ejuke", position: "FWD", ...R(72, 68, 25), rarity: "RARE", rating: 6.9 },
      { name: "Adrià Pedrosa", position: "DEF", ...R(50, 68, 78), rarity: "RARE", rating: 6.8 },
      { name: "Saúl Ñíguez", position: "MID", ...R(62, 76, 55), rarity: "RARE", rating: 7.0 },
      { name: "Rafa Mir", position: "FWD", ...R(76, 60, 25), rarity: "RARE", rating: 6.8 },
    ],
  },
  {
    name: "Alavés", shortName: "ALA", country: "España",
    colors: { primary: "#005dbb", secondary: "#ffffff", accent: "#c8102e" },
    players: [
      { name: "Antonio Sivera", position: "GK", ...R(28, 58, 82), rarity: "RARE", rating: 6.9 },
      { name: "Rafa Marín", position: "DEF", ...R(40, 62, 80), rarity: "RARE", rating: 6.9 },
      { name: "Abdel Abqar", position: "DEF", ...R(35, 60, 78), rarity: "BASE", rating: 6.7 },
      { name: "Rubén Duarte", position: "DEF", ...R(50, 65, 78), rarity: "BASE", rating: 6.7 },
      { name: "Javi López", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.6 },
      { name: "Antonio Blanco", position: "MID", ...R(50, 76, 55), rarity: "BASE", rating: 6.8 },
      { name: "Jon Guridi", position: "MID", ...R(55, 74, 50), rarity: "BASE", rating: 6.8 },
      { name: "Carlos Benavídez", position: "MID", ...R(55, 72, 52), rarity: "BASE", rating: 6.7 },
      { name: "Luis Rioja", position: "FWD", ...R(74, 70, 28), rarity: "RARE", goals: 6, assists: 5, rating: 7.0 },
      { name: "Toni Martínez", position: "FWD", ...R(76, 62, 25), rarity: "RARE", goals: 14, assists: 2, rating: 7.1 },
      { name: "Kike García", position: "FWD", ...R(74, 60, 25), rarity: "RARE", goals: 5, assists: 3, rating: 6.9 },
      { name: "Ianis Hagi", position: "MID", ...R(68, 74, 35), rarity: "RARE", rating: 6.9 },
      { name: "Álvaro García", position: "MID", ...R(65, 70, 40), rarity: "BASE", rating: 6.7 },
      { name: "Jesús Owono", position: "GK", ...R(25, 55, 78), rarity: "BASE", rating: 6.6 },
      { name: "Ander Guevara", position: "MID", ...R(50, 74, 58), rarity: "BASE", rating: 6.8 },
      { name: "Aleksandar Sedlar", position: "DEF", ...R(35, 60, 78), rarity: "BASE", rating: 6.7 },
    ],
  },
  {
    name: "Elche", shortName: "ELC", country: "España",
    colors: { primary: "#008000", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Miguel San Román", position: "GK", ...R(25, 56, 80), rarity: "BASE", rating: 6.7 },
      { name: "David Affengruber", position: "DEF", ...R(35, 60, 78), rarity: "BASE", rating: 6.7 },
      { name: "Pedro Bigas", position: "DEF", ...R(35, 58, 78), rarity: "BASE", rating: 6.6 },
      { name: "Lautaro Blanco", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Mario Gaspar", position: "DEF", ...R(45, 62, 76), rarity: "BASE", rating: 6.6 },
      { name: "Raúl Guti", position: "MID", ...R(55, 74, 50), rarity: "BASE", rating: 6.8 },
      { name: "Cristian Salvador", position: "MID", ...R(50, 70, 55), rarity: "BASE", rating: 6.6 },
      { name: "Nicolás Castro", position: "MID", ...R(60, 74, 42), rarity: "RARE", rating: 6.9 },
      { name: "Josán Fernández", position: "FWD", ...R(68, 65, 25), rarity: "BASE", rating: 6.7 },
      { name: "Sergio León", position: "FWD", ...R(72, 62, 25), rarity: "RARE", goals: 8, assists: 3, rating: 7.0 },
      { name: "Mourad", position: "FWD", ...R(70, 60, 22), rarity: "BASE", rating: 6.6 },
      { name: "Eder Sarabia", position: "MID", ...R(55, 72, 45), rarity: "BASE", rating: 6.7 },
      { name: "Arnau Puigmal", position: "MID", ...R(58, 72, 42), rarity: "BASE", rating: 6.7 },
      { name: "Clément Lenglet", position: "DEF", ...R(40, 68, 82), rarity: "RARE", rating: 6.9 },
      { name: "José Salinas", position: "FWD", ...R(68, 62, 25), rarity: "BASE", rating: 6.6 },
      { name: "Álex Collado", position: "MID", ...R(62, 72, 35), rarity: "RARE", rating: 6.8 },
    ],
  },
  {
    name: "Levante", shortName: "LEV", country: "España",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Andrés Fernández", position: "GK", ...R(25, 56, 82), rarity: "RARE", rating: 6.8 },
      { name: "Sergio Postigo", position: "DEF", ...R(35, 60, 78), rarity: "BASE", rating: 6.7 },
      { name: "Rober", position: "DEF", ...R(35, 58, 76), rarity: "BASE", rating: 6.6 },
      { name: "Álex Valle", position: "DEF", ...R(50, 65, 76), rarity: "RARE", rating: 6.8 },
      { name: "Andoni Gorosabel", position: "DEF", ...R(50, 65, 78), rarity: "RARE", rating: 6.8 },
      { name: "Iván Romero", position: "MID", ...R(55, 72, 50), rarity: "BASE", rating: 6.7 },
      { name: "Oriol Rey", position: "MID", ...R(50, 72, 55), rarity: "BASE", rating: 6.7 },
      { name: "Pablo Martínez", position: "MID", ...R(58, 75, 48), rarity: "RARE", rating: 6.9 },
      { name: "Carlos Espí", position: "FWD", ...R(72, 66, 25), rarity: "EPIC", goals: 9, assists: 4, rating: 7.2 },
      { name: "Fabricio Díaz", position: "MID", ...R(55, 74, 50), rarity: "BASE", rating: 6.8 },
      { name: "Roger Brugué", position: "FWD", ...R(70, 65, 28), rarity: "BASE", rating: 6.8 },
      { name: "Giorgi Kochorashvili", position: "MID", ...R(58, 72, 48), rarity: "RARE", rating: 6.8 },
      { name: "Dani Gómez", position: "FWD", ...R(72, 62, 25), rarity: "RARE", goals: 7, assists: 2, rating: 6.9 },
      { name: "Marc Pubill", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Ángel Algobia", position: "MID", ...R(50, 68, 52), rarity: "BASE", rating: 6.6 },
      { name: "Mohamed Bouldini", position: "FWD", ...R(70, 58, 22), rarity: "BASE", rating: 6.6 },
    ],
  },
  {
    name: "Osasuna", shortName: "OSA", country: "España",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Sergio Herrera", position: "GK", ...R(28, 58, 84), rarity: "RARE", rating: 7.0 },
      { name: "Dani Calvo", position: "DEF", ...R(35, 60, 80), rarity: "BASE", rating: 6.8 },
      { name: "Alejandro Catena", position: "DEF", ...R(40, 62, 80), rarity: "RARE", rating: 6.9 },
      { name: "Juan Cruz", position: "DEF", ...R(50, 65, 78), rarity: "BASE", rating: 6.7 },
      { name: "Jesús Areso", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Lucas Torró", position: "MID", ...R(50, 76, 60), rarity: "RARE", rating: 6.9 },
      { name: "Aimar Oroz", position: "MID", ...R(62, 78, 45), rarity: "RARE", rating: 7.1 },
      { name: "Moi Gómez", position: "MID", ...R(65, 76, 42), rarity: "RARE", rating: 7.0 },
      { name: "Ante Budimir", position: "FWD", ...R(82, 62, 28), rarity: "EPIC", goals: 17, assists: 3, rating: 7.4 },
      { name: "Rubén García", position: "FWD", ...R(74, 72, 30), rarity: "RARE", goals: 5, assists: 4, rating: 7.0 },
      { name: "Raúl García", position: "FWD", ...R(72, 68, 28), rarity: "RARE", rating: 6.9 },
      { name: "Kike Barja", position: "FWD", ...R(70, 65, 28), rarity: "BASE", rating: 6.7 },
      { name: "Darko Brašanac", position: "MID", ...R(55, 72, 55), rarity: "BASE", rating: 6.7 },
      { name: "Pablo Ibáñez", position: "DEF", ...R(40, 60, 78), rarity: "BASE", rating: 6.7 },
      { name: "Iker Muñoz", position: "MID", ...R(55, 72, 50), rarity: "BASE", rating: 6.7 },
      { name: "Yunus Akgün", position: "FWD", ...R(72, 68, 25), rarity: "RARE", rating: 6.9 },
    ],
  },
  {
    name: "Mallorca", shortName: "MLL", country: "España",
    colors: { primary: "#c8102e", secondary: "#000000", accent: "#ffcc00" },
    players: [
      { name: "Dominik Greif", position: "GK", ...R(28, 58, 82), rarity: "RARE", rating: 6.9 },
      { name: "Antonio Raíllo", position: "DEF", ...R(35, 62, 82), rarity: "RARE", rating: 7.0 },
      { name: "Valery Fernández", position: "DEF", ...R(50, 66, 78), rarity: "BASE", rating: 6.7 },
      { name: "Martín Valjent", position: "DEF", ...R(35, 62, 80), rarity: "BASE", rating: 6.8 },
      { name: "Pablo Maffeo", position: "DEF", ...R(55, 68, 78), rarity: "RARE", rating: 6.9 },
      { name: "Dani Rodríguez", position: "MID", ...R(62, 78, 45), rarity: "RARE", rating: 7.0 },
      { name: "Manu Morlanes", position: "MID", ...R(55, 75, 55), rarity: "RARE", rating: 6.9 },
      { name: "Samú Costa", position: "MID", ...R(50, 72, 60), rarity: "BASE", rating: 6.8 },
      { name: "Sergi Darder", position: "MID", ...R(68, 80, 48), rarity: "EPIC", goals: 5, assists: 5, rating: 7.2 },
      { name: "Vedat Muriqi", position: "FWD", ...R(86, 65, 28), rarity: "GOLDEN", goals: 23, assists: 4, rating: 7.6 },
      { name: "Cyle Larin", position: "FWD", ...R(76, 65, 25), rarity: "RARE", goals: 6, assists: 3, rating: 7.0 },
      { name: "Abdón Prats", position: "FWD", ...R(72, 62, 25), rarity: "BASE", rating: 6.8 },
      { name: "Johan Mojica", position: "DEF", ...R(55, 68, 76), rarity: "RARE", rating: 6.8 },
      { name: "Toni Lato", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.6 },
      { name: "Iván Sánchez", position: "MID", ...R(60, 72, 40), rarity: "BASE", rating: 6.7 },
      { name: "Clément Grenier", position: "MID", ...R(60, 76, 40), rarity: "RARE", rating: 6.9 },
    ],
  },
  {
    name: "Girona", shortName: "GIR", country: "España",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Paulo Gazzaniga", position: "GK", ...R(28, 58, 84), rarity: "RARE", rating: 7.0 },
      { name: "Daley Blind", position: "DEF", ...R(55, 78, 82), rarity: "EPIC", rating: 7.1 },
      { name: "David López", position: "DEF", ...R(40, 65, 82), rarity: "RARE", rating: 6.9 },
      { name: "Miguel Gutiérrez", position: "DEF", ...R(60, 72, 76), rarity: "EPIC", rating: 7.1 },
      { name: "Yan Couto", position: "DEF", ...R(62, 72, 72), rarity: "EPIC", rating: 7.1 },
      { name: "Aleix García", position: "MID", ...R(65, 84, 55), rarity: "EPIC", rating: 7.3 },
      { name: "Yangel Herrera", position: "MID", ...R(60, 76, 62), rarity: "RARE", rating: 7.0 },
      { name: "Iván Martín", position: "MID", ...R(62, 80, 48), rarity: "RARE", rating: 7.1 },
      { name: "Viktor Tsygankov", position: "FWD", ...R(78, 76, 30), rarity: "EPIC", goals: 6, assists: 5, rating: 7.2 },
      { name: "Cristhian Stuani", position: "FWD", ...R(78, 65, 28), rarity: "RARE", goals: 5, assists: 2, rating: 7.0 },
      { name: "Portu", position: "FWD", ...R(74, 70, 30), rarity: "RARE", rating: 6.9 },
      { name: "Abel Ruiz", position: "FWD", ...R(72, 68, 28), rarity: "RARE", rating: 6.8 },
      { name: "Jhon Solís", position: "MID", ...R(55, 72, 50), rarity: "BASE", rating: 6.7 },
      { name: "Arnau Puigmal", position: "MID", ...R(58, 72, 42), rarity: "BASE", rating: 6.7 },
      { name: "Toni Villa", position: "MID", ...R(62, 72, 38), rarity: "BASE", rating: 6.7 },
      { name: "Juanpe", position: "DEF", ...R(35, 62, 78), rarity: "BASE", rating: 6.7 },
    ],
  },
  {
    name: "Real Oviedo", shortName: "OVD", country: "España",
    colors: { primary: "#005dbb", secondary: "#ffffff", accent: "#c8102e" },
    players: [
      { name: "Quentin Braat", position: "GK", ...R(28, 56, 80), rarity: "BASE", rating: 6.7 },
      { name: "David Costas", position: "DEF", ...R(35, 60, 78), rarity: "BASE", rating: 6.6 },
      { name: "Dani Calvo", position: "DEF", ...R(35, 60, 78), rarity: "BASE", rating: 6.7 },
      { name: "Rodri Tarín", position: "FWD", ...R(68, 62, 25), rarity: "BASE", rating: 6.6 },
      { name: "Mario Hernández", position: "DEF", ...R(50, 62, 74), rarity: "BASE", rating: 6.5 },
      { name: "Jimmy Suárez", position: "MID", ...R(50, 70, 50), rarity: "BASE", rating: 6.6 },
      { name: "Santi Cazorla", position: "MID", ...R(72, 85, 35), rarity: "EPIC", goals: 4, assists: 5, rating: 7.2 },
      { name: "Jordi Mboula", position: "FWD", ...R(72, 65, 25), rarity: "RARE", rating: 6.8 },
      { name: "Fran Martínez", position: "FWD", ...R(68, 62, 25), rarity: "BASE", rating: 6.6 },
      { name: "Borja Bastón", position: "FWD", ...R(72, 60, 25), rarity: "RARE", goals: 6, assists: 2, rating: 6.9 },
      { name: "Héctor Hernández", position: "FWD", ...R(68, 62, 25), rarity: "BASE", rating: 6.6 },
      { name: "Lucas", position: "FWD", ...R(68, 60, 22), rarity: "BASE", rating: 6.5 },
      { name: "Jaime Seoane", position: "MID", ...R(55, 72, 48), rarity: "BASE", rating: 6.7 },
      { name: "Alejandro Rego", position: "GK", ...R(25, 55, 78), rarity: "BASE", rating: 6.5 },
      { name: "Sergio Lozano", position: "MID", ...R(52, 68, 45), rarity: "BASE", rating: 6.5 },
      { name: "Aarón Escandell", position: "GK", ...R(25, 55, 78), rarity: "BASE", rating: 6.5 },
    ],
  },
];
