import type { LigaTeamData } from "./liga-data";

const R = (a: number, c: number, d: number) => ({
  attack: a, control: c, defense: d, total: Math.round((a + c + d) / 3)
});

export const NATIONAL_TEAMS: LigaTeamData[] = [
  {
    name: "Spain", shortName: "ESP", country: "España",
    colors: { primary: "#c60b1e", secondary: "#ffc400", accent: "#000000" },
    players: [
      { name: "David Raya", position: "GK", ...R(25, 62, 94), rarity: "LEGENDARY" },
      { name: "Rodri", position: "MID", ...R(65, 88, 82), rarity: "LEGENDARY" },
      { name: "Pedri", position: "MID", ...R(72, 92, 68), rarity: "LEGENDARY" },
      { name: "Lamine Yamal", position: "FWD", ...R(90, 85, 35), rarity: "ULTRA_RARE" },
      { name: "Ferran Torres", position: "FWD", ...R(85, 72, 40), rarity: "GOLDEN" },
      { name: "Pau Cubarsí", position: "DEF", ...R(45, 70, 90), rarity: "EPIC" },
      { name: "Nico Williams", position: "FWD", ...R(86, 76, 30), rarity: "GOLDEN" },
      { name: "Fermín López", position: "MID", ...R(78, 85, 60), rarity: "EPIC" },
      { name: "Gavi", position: "MID", ...R(65, 88, 65), rarity: "EPIC" },
      { name: "Dani Olmo", position: "MID", ...R(80, 85, 55), rarity: "EPIC" },
      { name: "Pau Torres", position: "DEF", ...R(45, 72, 86), rarity: "EPIC" },
      { name: "Pedri", position: "MID", ...R(72, 92, 68), rarity: "LEGENDARY" },
      { name: "Martín Zubimendi", position: "MID", ...R(55, 85, 68), rarity: "LEGENDARY" },
      { name: "Álex Baena", position: "MID", ...R(82, 85, 40), rarity: "EPIC" },
      { name: "Mikel Oyarzabal", position: "FWD", ...R(84, 78, 35), rarity: "GOLDEN" },
      { name: "Pedro Porro", position: "DEF", ...R(62, 76, 76), rarity: "EPIC" },
    ],
  },
  {
    name: "France", shortName: "FRA", country: "Francia",
    colors: { primary: "#002395", secondary: "#ffffff", accent: "#c60b1e" },
    players: [
      { name: "Kylian Mbappé", position: "FWD", ...R(97, 85, 30), rarity: "ULTRA_RARE" },
      { name: "Eduardo Camavinga", position: "MID", ...R(65, 85, 72), rarity: "EPIC" },
      { name: "Aurélien Tchouaméni", position: "MID", ...R(55, 80, 78), rarity: "EPIC" },
      { name: "William Saliba", position: "DEF", ...R(45, 72, 92), rarity: "LEGENDARY" },
      { name: "Jules Koundé", position: "DEF", ...R(55, 74, 86), rarity: "RARE" },
      { name: "Wesley Fofana", position: "DEF", ...R(40, 65, 84), rarity: "RARE" },
      { name: "Lucas Digne", position: "DEF", ...R(55, 72, 80), rarity: "RARE" },
      { name: "Boubacar Kamara", position: "MID", ...R(50, 76, 65), rarity: "RARE" },
      { name: "Christopher Nkunku", position: "FWD", ...R(82, 82, 35), rarity: "EPIC" },
      { name: "Mason Greenwood", position: "FWD", ...R(80, 72, 30), rarity: "EPIC" },
      { name: "Michael Olise", position: "MID", ...R(80, 82, 35), rarity: "EPIC" },
      { name: "Jean-Philippe Mateta", position: "FWD", ...R(80, 68, 28), rarity: "RARE" },
      { name: "Odsonne Edouard", position: "FWD", ...R(76, 68, 25), rarity: "RARE" },
      { name: "Alphonse Areola", position: "GK", ...R(28, 58, 84), rarity: "RARE" },
      { name: "Kurt Zouma", position: "DEF", ...R(40, 65, 84), rarity: "RARE" },
      { name: "Raphaël Varane", position: "DEF", ...R(40, 68, 88), rarity: "EPIC" },
    ],
  },
  {
    name: "Brazil", shortName: "BRA", country: "Brasil",
    colors: { primary: "#009c3b", secondary: "#ffdf00", accent: "#002776" },
    players: [
      { name: "Vinícius Júnior", position: "FWD", ...R(92, 78, 30), rarity: "GOLDEN" },
      { name: "Rodrygo", position: "FWD", ...R(82, 80, 35), rarity: "EPIC" },
      { name: "Raphinha", position: "FWD", ...R(82, 75, 35), rarity: "EPIC" },
      { name: "Éder Militão", position: "DEF", ...R(45, 72, 88), rarity: "EPIC" },
      { name: "Gabriel", position: "DEF", ...R(40, 68, 90), rarity: "EPIC" },
      { name: "Gabriel Martinelli", position: "FWD", ...R(84, 76, 30), rarity: "EPIC" },
      { name: "Joelinton", position: "MID", ...R(72, 76, 60), rarity: "RARE" },
      { name: "Bruno Guimarães", position: "MID", ...R(65, 85, 68), rarity: "EPIC" },
      { name: "Douglas Luiz", position: "MID", ...R(62, 84, 60), rarity: "EPIC" },
      { name: "Casemiro", position: "MID", ...R(50, 76, 72), rarity: "RARE" },
      { name: "João Pedro", position: "FWD", ...R(82, 74, 30), rarity: "EPIC" },
      { name: "Murillo", position: "DEF", ...R(45, 68, 84), rarity: "EPIC" },
      { name: "Danilo", position: "MID", ...R(58, 74, 50), rarity: "RARE" },
      { name: "Andreas Pereira", position: "MID", ...R(72, 82, 45), rarity: "EPIC" },
      { name: "Alisson Becker", position: "GK", ...R(25, 60, 92), rarity: "LEGENDARY" },
      { name: "Richarlison", position: "FWD", ...R(80, 68, 30), rarity: "RARE" },
    ],
  },
  {
    name: "Argentina", shortName: "ARG", country: "Argentina",
    colors: { primary: "#75aadb", secondary: "#ffffff", accent: "#ffcc00" },
    players: [
      { name: "Emiliano Martínez", position: "GK", ...R(28, 60, 90), rarity: "LEGENDARY" },
      { name: "Julián Alvarez", position: "FWD", ...R(88, 78, 35), rarity: "GOLDEN" },
      { name: "Enzo Fernández", position: "MID", ...R(68, 85, 58), rarity: "EPIC" },
      { name: "Alexis Mac Allister", position: "MID", ...R(72, 86, 58), rarity: "EPIC" },
      { name: "Cristian Romero", position: "DEF", ...R(50, 68, 86), rarity: "EPIC" },
      { name: "Lisandro Martínez", position: "DEF", ...R(45, 72, 86), rarity: "EPIC" },
      { name: "Alejandro Garnacho", position: "FWD", ...R(82, 74, 28), rarity: "EPIC" },
      { name: "Lautaro Blanco", position: "DEF", ...R(50, 65, 76), rarity: "BASE" },
      { name: "Nicolás Castro", position: "MID", ...R(60, 74, 42), rarity: "RARE" },
      { name: "Ángel Correa", position: "FWD", ...R(78, 72, 30), rarity: "RARE" },
      { name: "Marcos Acuña", position: "DEF", ...R(60, 72, 78), rarity: "RARE" },
      { name: "Paulo Gazzaniga", position: "GK", ...R(28, 58, 84), rarity: "RARE" },
      { name: "Chimy Ávila", position: "FWD", ...R(80, 65, 30), rarity: "RARE" },
      { name: "Marcos Senesi", position: "DEF", ...R(50, 72, 80), rarity: "RARE" },
      { name: "Rodrigo De Paul", position: "MID", ...R(72, 82, 60), rarity: "EPIC" },
      { name: "Nicolas Jackson", position: "FWD", ...R(80, 68, 25), rarity: "RARE" },
    ],
  },
  {
    name: "England", shortName: "ENG", country: "Inglaterra",
    colors: { primary: "#ffffff", secondary: "#c60b1e", accent: "#005dbb" },
    players: [
      { name: "Jordan Pickford", position: "GK", ...R(28, 62, 88), rarity: "LEGENDARY" },
      { name: "Jude Bellingham", position: "MID", ...R(85, 82, 65), rarity: "LEGENDARY" },
      { name: "Cole Palmer", position: "MID", ...R(86, 84, 40), rarity: "GOLDEN" },
      { name: "Phil Foden", position: "MID", ...R(86, 88, 40), rarity: "GOLDEN" },
      { name: "Bukayo Saka", position: "FWD", ...R(88, 82, 35), rarity: "LEGENDARY" },
      { name: "Declan Rice", position: "MID", ...R(68, 85, 82), rarity: "LEGENDARY" },
      { name: "Trent Alexander-Arnold", position: "DEF", ...R(82, 88, 72), rarity: "GOLDEN" },
      { name: "Kieran Trippier", position: "DEF", ...R(72, 82, 80), rarity: "LEGENDARY" },
      { name: "Marc Guéhi", position: "DEF", ...R(45, 72, 86), rarity: "EPIC" },
      { name: "Dominic Calvert-Lewin", position: "FWD", ...R(80, 65, 28), rarity: "EPIC" },
      { name: "Morgan Gibbs-White", position: "MID", ...R(82, 82, 42), rarity: "GOLDEN" },
      { name: "Jack Grealish", position: "FWD", ...R(78, 80, 30), rarity: "EPIC" },
      { name: "James Ward-Prowse", position: "MID", ...R(72, 82, 55), rarity: "EPIC" },
      { name: "Jarrod Bowen", position: "FWD", ...R(84, 76, 35), rarity: "EPIC" },
      { name: "Kyle Walker", position: "DEF", ...R(60, 72, 82), rarity: "RARE" },
      { name: "Harry Kane", position: "FWD", ...R(92, 78, 30), rarity: "ULTRA_RARE" },
    ],
  },
  {
    name: "Portugal", shortName: "POR", country: "Portugal",
    colors: { primary: "#c60b1e", secondary: "#006600", accent: "#ffcc00" },
    players: [
      { name: "Rúben Dias", position: "DEF", ...R(40, 70, 90), rarity: "LEGENDARY" },
      { name: "Bruno Fernandes", position: "MID", ...R(86, 88, 48), rarity: "GOLDEN" },
      { name: "Bernardo Silva", position: "MID", ...R(72, 88, 55), rarity: "LEGENDARY" },
      { name: "Diogo Dalot", position: "DEF", ...R(55, 72, 80), rarity: "RARE" },
      { name: "Matheus Nunes", position: "MID", ...R(65, 78, 50), rarity: "RARE" },
      { name: "Nélson Semedo", position: "DEF", ...R(52, 68, 78), rarity: "RARE" },
      { name: "José Sá", position: "GK", ...R(28, 58, 82), rarity: "RARE" },
      { name: "André Almeida", position: "MID", ...R(68, 75, 48), rarity: "RARE" },
      { name: "João Gomes", position: "MID", ...R(55, 76, 62), rarity: "RARE" },
      { name: "Fabio Silva", position: "FWD", ...R(72, 65, 22), rarity: "RARE" },
    ],
  },
  {
    name: "Germany", shortName: "GER", country: "Alemania",
    colors: { primary: "#000000", secondary: "#c60b1e", accent: "#ffcc00" },
    players: [
      { name: "Antonio Rüdiger", position: "DEF", ...R(50, 68, 90), rarity: "EPIC" },
      { name: "Kai Havertz", position: "MID", ...R(78, 78, 48), rarity: "EPIC" },
      { name: "Bernd Leno", position: "GK", ...R(28, 60, 86), rarity: "EPIC" },
      { name: "Niklas Füllkrug", position: "FWD", ...R(80, 62, 25), rarity: "RARE" },
      { name: "Timo Werner", position: "FWD", ...R(76, 70, 25), rarity: "RARE" },
      { name: "Vitaly Janelt", position: "MID", ...R(55, 76, 60), rarity: "RARE" },
      { name: "Kevin Schade", position: "FWD", ...R(76, 70, 28), rarity: "RARE" },
      { name: "Jordan Beyer", position: "DEF", ...R(35, 62, 78), rarity: "BASE" },
    ],
  },
  {
    name: "Netherlands", shortName: "NED", country: "Países Bajos",
    colors: { primary: "#ff6600", secondary: "#ffffff", accent: "#c60b1e" },
    players: [
      { name: "Virgil van Dijk", position: "DEF", ...R(50, 76, 92), rarity: "LEGENDARY" },
      { name: "Frenkie de Jong", position: "MID", ...R(68, 88, 72), rarity: "LEGENDARY" },
      { name: "Ryan Gravenberch", position: "MID", ...R(65, 82, 55), rarity: "EPIC" },
      { name: "Jurriën Timber", position: "DEF", ...R(60, 76, 86), rarity: "EPIC" },
      { name: "Micky van de Ven", position: "DEF", ...R(45, 70, 84), rarity: "EPIC" },
      { name: "Cody Gakpo", position: "FWD", ...R(80, 76, 30), rarity: "EPIC" },
      { name: "Bart Verbruggen", position: "GK", ...R(28, 60, 86), rarity: "EPIC" },
      { name: "Daley Blind", position: "DEF", ...R(55, 78, 82), rarity: "EPIC" },
      { name: "Ian Maatsen", position: "DEF", ...R(55, 72, 76), rarity: "RARE" },
      { name: "Joël Veltman", position: "DEF", ...R(45, 68, 80), rarity: "RARE" },
      { name: "Mark Flekken", position: "GK", ...R(28, 60, 84), rarity: "RARE" },
      { name: "Justin Kluivert", position: "FWD", ...R(76, 72, 28), rarity: "RARE" },
      { name: "Crysencio Summerville", position: "FWD", ...R(78, 72, 28), rarity: "RARE" },
      { name: "Joel Piroe", position: "FWD", ...R(74, 70, 25), rarity: "RARE" },
      { name: "Jan Paul van Hecke", position: "DEF", ...R(40, 65, 82), rarity: "RARE" },
      { name: "Sven Botman", position: "DEF", ...R(40, 68, 86), rarity: "EPIC" },
    ],
  },
  {
    name: "Italy", shortName: "ITA", country: "Italia",
    colors: { primary: "#005dbb", secondary: "#ffffff", accent: "#c60b1e" },
    players: [
      { name: "Gianluigi Donnarumma", position: "GK", ...R(25, 58, 92), rarity: "LEGENDARY" },
      { name: "Sandro Tonali", position: "MID", ...R(65, 82, 65), rarity: "EPIC" },
      { name: "Riccardo Calafiori", position: "DEF", ...R(55, 72, 82), rarity: "RARE" },
      { name: "Guglielmo Vicario", position: "GK", ...R(28, 60, 86), rarity: "EPIC" },
      { name: "Destiny Udogie", position: "DEF", ...R(58, 72, 78), rarity: "EPIC" },
      { name: "Emerson Palmieri", position: "DEF", ...R(55, 72, 78), rarity: "RARE" },
      { name: "Nicolas Dominguez", position: "MID", ...R(60, 74, 52), rarity: "RARE" },
      { name: "Wilfried Gnonto", position: "FWD", ...R(76, 72, 25), rarity: "RARE" },
      { name: "Luca Koleosho", position: "FWD", ...R(72, 68, 22), rarity: "RARE" },
    ],
  },
  {
    name: "Belgium", shortName: "BEL", country: "Bélgica",
    colors: { primary: "#c60b1e", secondary: "#ffcc00", accent: "#000000" },
    players: [
      { name: "Kevin De Bruyne", position: "MID", ...R(88, 92, 45), rarity: "ULTRA_RARE" },
      { name: "Thibaut Courtois", position: "GK", ...R(25, 60, 95), rarity: "LEGENDARY" },
      { name: "Jérémy Doku", position: "FWD", ...R(84, 74, 28), rarity: "EPIC" },
      { name: "Leandro Trossard", position: "FWD", ...R(80, 76, 30), rarity: "RARE" },
      { name: "Youri Tielemans", position: "MID", ...R(65, 82, 55), rarity: "EPIC" },
      { name: "Amadou Onana", position: "MID", ...R(55, 78, 65), rarity: "EPIC" },
      { name: "Arthur Vermeeren", position: "MID", ...R(55, 75, 55), rarity: "RARE" },
      { name: "Roméo Lavia", position: "MID", ...R(55, 76, 60), rarity: "RARE" },
      { name: "Dodi Lukebakio", position: "FWD", ...R(80, 70, 28), rarity: "RARE" },
      { name: "Senne Lammens", position: "GK", ...R(25, 58, 82), rarity: "RARE" },
    ],
  },
  {
    name: "Uruguay", shortName: "URU", country: "Uruguay",
    colors: { primary: "#75aadb", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Federico Valverde", position: "MID", ...R(78, 82, 68), rarity: "LEGENDARY" },
      { name: "Ronald Araújo", position: "DEF", ...R(50, 72, 92), rarity: "LEGENDARY" },
      { name: "Darwin Núñez", position: "FWD", ...R(84, 65, 28), rarity: "EPIC" },
      { name: "Rodrigo Bentancur", position: "MID", ...R(58, 78, 58), rarity: "RARE" },
      { name: "Federico Viñas", position: "FWD", ...R(74, 62, 28), rarity: "RARE" },
      { name: "Manuel Ugarte", position: "MID", ...R(50, 74, 70), rarity: "RARE" },
      { name: "Santiago Mouriño", position: "DEF", ...R(50, 72, 86), rarity: "EPIC" },
      { name: "Cristhian Stuani", position: "FWD", ...R(78, 65, 28), rarity: "RARE" },
    ],
  },
  {
    name: "Morocco", shortName: "MAR", country: "Marruecos",
    colors: { primary: "#c60b1e", secondary: "#006600", accent: "#000000" },
    players: [
      { name: "Nayef Aguerd", position: "DEF", ...R(40, 68, 82), rarity: "RARE" },
      { name: "Brahim Díaz", position: "MID", ...R(75, 78, 35), rarity: "RARE" },
      { name: "Mohamed Bouldini", position: "FWD", ...R(70, 58, 22), rarity: "BASE" },
    ],
  },
  {
    name: "Norway", shortName: "NOR", country: "Noruega",
    colors: { primary: "#c60b1e", secondary: "#005dbb", accent: "#ffffff" },
    players: [
      { name: "Erling Haaland", position: "FWD", ...R(99, 70, 30), rarity: "ULTRA_RARE" },
      { name: "Martin Ødegaard", position: "MID", ...R(78, 90, 50), rarity: "GOLDEN" },
      { name: "Alexander Sørloth", position: "FWD", ...R(80, 60, 25), rarity: "RARE" },
      { name: "Sander Berge", position: "MID", ...R(55, 76, 62), rarity: "RARE" },
      { name: "Kristoffer Ajer", position: "DEF", ...R(45, 68, 80), rarity: "RARE" },
      { name: "Ørjan Nyland", position: "GK", ...R(28, 58, 82), rarity: "RARE" },
    ],
  },
  {
    name: "Croatia", shortName: "CRO", country: "Croacia",
    colors: { primary: "#c60b1e", secondary: "#ffffff", accent: "#005dbb" },
    players: [
      { name: "Ante Budimir", position: "FWD", ...R(82, 62, 28), rarity: "EPIC" },
      { name: "Josko Gvardiol", position: "DEF", ...R(60, 76, 86), rarity: "EPIC" },
      { name: "Luka Modrić", position: "MID", ...R(72, 92, 50), rarity: "LEGENDARY" },
    ],
  },
  {
    name: "Japan", shortName: "JPN", country: "Japón",
    colors: { primary: "#005dbb", secondary: "#ffffff", accent: "#c60b1e" },
    players: [
      { name: "Kaoru Mitoma", position: "FWD", ...R(86, 78, 30), rarity: "EPIC" },
      { name: "Takefusa Kubo", position: "FWD", ...R(82, 78, 30), rarity: "EPIC" },
      { name: "Wataru Endō", position: "MID", ...R(45, 72, 68), rarity: "RARE" },
    ],
  },
  {
    name: "Sweden", shortName: "SWE", country: "Suecia",
    colors: { primary: "#ffcc00", secondary: "#005dbb", accent: "#ffffff" },
    players: [
      { name: "Alexander Isak", position: "FWD", ...R(88, 78, 30), rarity: "GOLDEN" },
      { name: "Viktor Gyökeres", position: "FWD", ...R(88, 72, 30), rarity: "GOLDEN" },
      { name: "Dejan Kulusevski", position: "MID", ...R(78, 80, 42), rarity: "EPIC" },
      { name: "Anthony Elanga", position: "FWD", ...R(80, 72, 28), rarity: "RARE" },
    ],
  },
  {
    name: "Denmark", shortName: "DEN", country: "Dinamarca",
    colors: { primary: "#c60b1e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Christian Nørgaard", position: "MID", ...R(50, 78, 65), rarity: "RARE" },
      { name: "Mathias Jensen", position: "MID", ...R(60, 80, 50), rarity: "RARE" },
      { name: "Joachim Andersen", position: "DEF", ...R(40, 68, 84), rarity: "RARE" },
      { name: "Martin Braithwaite", position: "FWD", ...R(76, 65, 28), rarity: "RARE" },
      { name: "Andreas Christensen", position: "DEF", ...R(40, 70, 85), rarity: "RARE" },
      { name: "Rasmus Højlund", position: "FWD", ...R(82, 68, 28), rarity: "EPIC" },
      { name: "Jesper Lindstrøm", position: "MID", ...R(68, 74, 40), rarity: "RARE" },
      { name: "Matt O'Riley", position: "MID", ...R(65, 78, 45), rarity: "RARE" },
    ],
  },
  {
    name: "Ukraine", shortName: "UKR", country: "Ucrania",
    colors: { primary: "#005dbb", secondary: "#ffcc00", accent: "#ffffff" },
    players: [
      { name: "Viktor Tsygankov", position: "FWD", ...R(78, 76, 30), rarity: "EPIC" },
      { name: "Vitalii Mykolenko", position: "DEF", ...R(50, 68, 78), rarity: "RARE" },
      { name: "Mykhailo Mudryk", position: "FWD", ...R(78, 72, 25), rarity: "RARE" },
      { name: "Ilya Zabarnyi", position: "DEF", ...R(40, 65, 82), rarity: "RARE" },
    ],
  },
  {
    name: "Colombia", shortName: "COL", country: "Colombia",
    colors: { primary: "#ffcc00", secondary: "#005dbb", accent: "#c60b1e" },
    players: [
      { name: "Luis Díaz", position: "FWD", ...R(86, 78, 30), rarity: "EPIC" },
      { name: "Jhon Durán", position: "FWD", ...R(78, 62, 25), rarity: "RARE" },
      { name: "Daniel Muñoz", position: "DEF", ...R(55, 68, 78), rarity: "RARE" },
      { name: "Jefferson Lerma", position: "MID", ...R(55, 74, 65), rarity: "RARE" },
      { name: "Jhon Solís", position: "MID", ...R(55, 72, 50), rarity: "BASE" },
      { name: "Luis Sinisterra", position: "FWD", ...R(74, 72, 28), rarity: "RARE" },
      { name: "Johan Mojica", position: "DEF", ...R(55, 68, 76), rarity: "RARE" },
    ],
  },
  {
    name: "Nigeria", shortName: "NGA", country: "Nigeria",
    colors: { primary: "#008000", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Taiwo Awoniyi", position: "FWD", ...R(78, 65, 25), rarity: "RARE" },
      { name: "Alex Iwobi", position: "MID", ...R(68, 76, 48), rarity: "RARE" },
      { name: "Frank Onyeka", position: "MID", ...R(55, 72, 58), rarity: "BASE" },
      { name: "Calvin Bassey", position: "DEF", ...R(35, 62, 80), rarity: "RARE" },
      { name: "Ola Aina", position: "DEF", ...R(50, 68, 78), rarity: "RARE" },
      { name: "Samuel Chukwueze", position: "FWD", ...R(76, 72, 25), rarity: "RARE" },
      { name: "Kelechi Iheanacho", position: "FWD", ...R(74, 68, 25), rarity: "RARE" },
    ],
  },
  {
    name: "South Korea", shortName: "KOR", country: "Corea del Sur",
    colors: { primary: "#c60b1e", secondary: "#005dbb", accent: "#ffffff" },
    players: [
      { name: "Heung-min Son", position: "FWD", ...R(88, 78, 30), rarity: "LEGENDARY" },
      { name: "Hwang Hee-chan", position: "FWD", ...R(78, 70, 28), rarity: "RARE" },
    ],
  },
  {
    name: "Senegal", shortName: "SEN", country: "Senegal",
    colors: { primary: "#008000", secondary: "#ffcc00", accent: "#c60b1e" },
    players: [
      { name: "Pathé Ciss", position: "MID", ...R(55, 72, 65), rarity: "RARE" },
      { name: "Keita Baldé", position: "FWD", ...R(74, 68, 25), rarity: "RARE" },
      { name: "Iliman Ndiaye", position: "FWD", ...R(76, 72, 28), rarity: "RARE" },
      { name: "Nicolas Jackson", position: "FWD", ...R(80, 68, 25), rarity: "RARE" },
      { name: "Pape Matar Sarr", position: "MID", ...R(62, 78, 55), rarity: "EPIC" },
      { name: "Chidera Ejuke", position: "FWD", ...R(75, 68, 25), rarity: "RARE" },
      { name: "Abdou Diallo", position: "DEF", ...R(45, 68, 82), rarity: "RARE" },
    ],
  },
  {
    name: "Serbia", shortName: "SRB", country: "Serbia",
    colors: { primary: "#c60b1e", secondary: "#005dbb", accent: "#ffffff" },
    players: [
      { name: "Nemanja Gudelj", position: "MID", ...R(50, 72, 65), rarity: "RARE" },
      { name: "Darko Brašanac", position: "MID", ...R(55, 72, 55), rarity: "BASE" },
      { name: "Dušan Vlahović", position: "FWD", ...R(84, 65, 25), rarity: "EPIC" },
      { name: "Sergej Milinković-Savić", position: "MID", ...R(78, 84, 55), rarity: "EPIC" },
    ],
  },
  {
    name: "Ivory Coast", shortName: "CIV", country: "Costa de Marfil",
    colors: { primary: "#ff6600", secondary: "#008000", accent: "#ffffff" },
    players: [
      { name: "Nicolas Pépé", position: "FWD", ...R(82, 72, 30), rarity: "EPIC" },
      { name: "Seko Fofana", position: "MID", ...R(65, 78, 50), rarity: "RARE" },
      { name: "Amad Diallo", position: "FWD", ...R(76, 74, 30), rarity: "RARE" },
      { name: "Maxwel Cornet", position: "FWD", ...R(72, 65, 25), rarity: "RARE" },
      { name: "Ibrahim Sangaré", position: "MID", ...R(55, 78, 65), rarity: "RARE" },
    ],
  },
];
