// Mapa de nacionalidad real por jugador
// Formato: [nombre]: { country, flag (nombre seleccion) }
// Solo se incluyen jugadores cuya nacionalidad NO coincide con la liga

type NationalityMap = Record<string, { country: string; nationalTeam: string }>;

export const NOT_SPANISH: NationalityMap = {
  "Kylian Mbappé": { country: "Francia", nationalTeam: "France" },
  "Vedat Muriqi": { country: "Kosovo", nationalTeam: "Kosovo" },
  "Ante Budimir": { country: "Croacia", nationalTeam: "Croatia" },
  "Robert Lewandowski": { country: "Polonia", nationalTeam: "Poland" },
  "Ronald Araújo": { country: "Uruguay", nationalTeam: "Uruguay" },
  "Jules Koundé": { country: "Francia", nationalTeam: "France" },
  "Frenkie de Jong": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Andreas Christensen": { country: "Dinamarca", nationalTeam: "Denmark" },
  "Raphinha": { country: "Brasil", nationalTeam: "Brazil" },
  "João Pedro": { country: "Brasil", nationalTeam: "Brazil" },
  "Thibaut Courtois": { country: "Bélgica", nationalTeam: "Belgium" },
  "Antonio Rüdiger": { country: "Alemania", nationalTeam: "Germany" },
  "Éder Militão": { country: "Brasil", nationalTeam: "Brazil" },
  "David Alaba": { country: "Austria", nationalTeam: "Austria" },
  "Eduardo Camavinga": { country: "Francia", nationalTeam: "France" },
  "Federico Valverde": { country: "Uruguay", nationalTeam: "Uruguay" },
  "Aurélien Tchouaméni": { country: "Francia", nationalTeam: "France" },
  "Jude Bellingham": { country: "Inglaterra", nationalTeam: "England" },
  "Arda Güler": { country: "Turquía", nationalTeam: "Turkey" },
  "Vinícius Júnior": { country: "Brasil", nationalTeam: "Brazil" },
  "Rodrygo": { country: "Brasil", nationalTeam: "Brazil" },
  "Endrick": { country: "Brasil", nationalTeam: "Brazil" },
  "Brahim Díaz": { country: "Marruecos", nationalTeam: "Morocco" },
  "Luiz Júnior": { country: "Brasil", nationalTeam: "Brazil" },
  "Santiago Mouriño": { country: "Uruguay", nationalTeam: "Uruguay" },
  "Raúl Albiol": { country: "España", nationalTeam: "Spain" },
  "Nicolas Pépé": { country: "Costa de Marfil", nationalTeam: "Ivory Coast" },
  "Thierno Barry": { country: "Francia", nationalTeam: "France" },
  "Pape Gueye": { country: "Senegal", nationalTeam: "Senegal" },
  "Tajon Buchanan": { country: "Canadá", nationalTeam: "Canada" },
  "Koke": { country: "España", nationalTeam: "Spain" },
  "Julián Alvarez": { country: "Argentina", nationalTeam: "Argentina" },
  "Antoine Griezmann": { country: "Francia", nationalTeam: "France" },
  "Ángel Correa": { country: "Argentina", nationalTeam: "Argentina" },
  "Alexander Sørloth": { country: "Noruega", nationalTeam: "Norway" },
  "Arthur Vermeeren": { country: "Bélgica", nationalTeam: "Belgium" },
  "César Azpilicueta": { country: "España", nationalTeam: "Spain" },
  "Marcos Acuña": { country: "Argentina", nationalTeam: "Argentina" },
  "Loïc Badé": { country: "Francia", nationalTeam: "France" },
  "Nemanja Gudelj": { country: "Serbia", nationalTeam: "Serbia" },
  "Albert Sambi Lokonga": { country: "Bélgica", nationalTeam: "Belgium" },
  "Lucien Agoumé": { country: "Francia", nationalTeam: "France" },
  "Dodi Lukebakio": { country: "Bélgica", nationalTeam: "Belgium" },
  "Saúl Ñíguez": { country: "España", nationalTeam: "Spain" },
  "Rafa Marín": { country: "España", nationalTeam: "Spain" },
  "Ianis Hagi": { country: "Rumanía", nationalTeam: "Romania" },
  "Santi Cazorla": { country: "España", nationalTeam: "Spain" },
  "Mason Greenwood": { country: "Inglaterra", nationalTeam: "England" },
  "Chidera Ejuke": { country: "Nigeria", nationalTeam: "Nigeria" },
  "Nemanja Maksimović": { country: "Serbia", nationalTeam: "Serbia" },
  "Pathé Ciss": { country: "Senegal", nationalTeam: "Senegal" },
  "Raúl de Tomás": { country: "España", nationalTeam: "Spain" },
  "Giorgi Mamardashvili": { country: "Georgia", nationalTeam: "Georgia" },
  "Mouctar Diakhaby": { country: "Francia", nationalTeam: "France" },
  "André Almeida": { country: "Portugal", nationalTeam: "Portugal" },
  "Federico Viñas": { country: "Uruguay", nationalTeam: "Uruguay" },
  "Takefusa Kubo": { country: "Japón", nationalTeam: "Japan" },
  "Sheraldo Becker": { country: "Surinam", nationalTeam: "Suriname" },
  "Arsen Zakharyan": { country: "Rusia", nationalTeam: "Russia" },
  "Martin Braithwaite": { country: "Dinamarca", nationalTeam: "Denmark" },
  "Keita Baldé": { country: "Senegal", nationalTeam: "Senegal" },
  "Nico Melamed": { country: "España", nationalTeam: "Spain" },
  "Nico Williams": { country: "España", nationalTeam: "Spain" },
  "Iñaki Williams": { country: "Ghana", nationalTeam: "Ghana" },
  "Yuri Berchiche": { country: "España", nationalTeam: "Spain" },
  "Orjan Nyland": { country: "Noruega", nationalTeam: "Norway" },
  "Suso": { country: "España", nationalTeam: "Spain" },
  "Adrià Pedrosa": { country: "España", nationalTeam: "Spain" },
  "Rafa Mir": { country: "España", nationalTeam: "Spain" },
  "Toni Martínez": { country: "España", nationalTeam: "Spain" },
  "Kike García": { country: "España", nationalTeam: "Spain" },
  "Lautaro Blanco": { country: "Argentina", nationalTeam: "Argentina" },
  "Nicolás Castro": { country: "Argentina", nationalTeam: "Argentina" },
  "Álex Collado": { country: "España", nationalTeam: "Spain" },
  "Fabricio Díaz": { country: "Uruguay", nationalTeam: "Uruguay" },
  "Mohamed Bouldini": { country: "Marruecos", nationalTeam: "Morocco" },
  "Darko Brašanac": { country: "Serbia", nationalTeam: "Serbia" },
  "Yunus Akgün": { country: "Turquía", nationalTeam: "Turkey" },
  "Dominik Greif": { country: "Eslovaquia", nationalTeam: "Slovakia" },
  "Cyle Larin": { country: "Canadá", nationalTeam: "Canada" },
  "Johan Mojica": { country: "Colombia", nationalTeam: "Colombia" },
  "Clément Grenier": { country: "Francia", nationalTeam: "France" },
  "Daley Blind": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Yan Couto": { country: "Brasil", nationalTeam: "Brazil" },
  "Yangel Herrera": { country: "Venezuela", nationalTeam: "Venezuela" },
  "Viktor Tsygankov": { country: "Ucrania", nationalTeam: "Ukraine" },
  "Cristhian Stuani": { country: "Uruguay", nationalTeam: "Uruguay" },
  "Portu": { country: "España", nationalTeam: "Spain" },
  "Jhon Solís": { country: "Colombia", nationalTeam: "Colombia" },
  "Paulo Gazzaniga": { country: "Argentina", nationalTeam: "Argentina" },
  "Sérginho Dest": { country: "EE.UU.", nationalTeam: "USA" },
  "Isco": { country: "España", nationalTeam: "Spain" },
  "Chimy Ávila": { country: "Argentina", nationalTeam: "Argentina" },
  "Vitor Roque": { country: "Brasil", nationalTeam: "Brazil" },
  "Assane Diao": { country: "Senegal", nationalTeam: "Senegal" },
  "Johnny Cardoso": { country: "EE.UU.", nationalTeam: "USA" },
  "Romain Perraud": { country: "Francia", nationalTeam: "France" },
  "Nabil Fikrir": { country: "Francia", nationalTeam: "France" },
};

export const NOT_ENGLISH: NationalityMap = {
  "David Raya": { country: "España", nationalTeam: "Spain" },
  "William Saliba": { country: "Francia", nationalTeam: "France" },
  "Gabriel": { country: "Brasil", nationalTeam: "Brazil" },
  "Jurriën Timber": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Martin Ødegaard": { country: "Noruega", nationalTeam: "Norway" },
  "Viktor Gyökeres": { country: "Suecia", nationalTeam: "Sweden" },
  "Gabriel Martinelli": { country: "Brasil", nationalTeam: "Brazil" },
  "Kai Havertz": { country: "Alemania", nationalTeam: "Germany" },
  "Leandro Trossard": { country: "Bélgica", nationalTeam: "Belgium" },
  "Riccardo Calafiori": { country: "Italia", nationalTeam: "Italy" },
  "Thomas Partey": { country: "Ghana", nationalTeam: "Ghana" },
  "Martin Zubimendi": { country: "España", nationalTeam: "Spain" },
  "Mikel Merino": { country: "España", nationalTeam: "Spain" },
  "Gianluigi Donnarumma": { country: "Italia", nationalTeam: "Italy" },
  "Rúben Dias": { country: "Portugal", nationalTeam: "Portugal" },
  "John Stones": { country: "Inglaterra", nationalTeam: "England" },
  "Josko Gvardiol": { country: "Croacia", nationalTeam: "Croatia" },
  "Kyle Walker": { country: "Inglaterra", nationalTeam: "England" },
  "Rodri": { country: "España", nationalTeam: "Spain" },
  "Kevin De Bruyne": { country: "Bélgica", nationalTeam: "Belgium" },
  "Phil Foden": { country: "Inglaterra", nationalTeam: "England" },
  "Erling Haaland": { country: "Noruega", nationalTeam: "Norway" },
  "Jérémy Doku": { country: "Bélgica", nationalTeam: "Belgium" },
  "Bernardo Silva": { country: "Portugal", nationalTeam: "Portugal" },
  "Matheus Nunes": { country: "Portugal", nationalTeam: "Portugal" },
  "Rico Lewis": { country: "Inglaterra", nationalTeam: "England" },
  "Jack Grealish": { country: "Inglaterra", nationalTeam: "England" },
  "Sávio": { country: "Brasil", nationalTeam: "Brazil" },
  "André Onana": { country: "Camerún", nationalTeam: "Cameroon" },
  "Lisandro Martínez": { country: "Argentina", nationalTeam: "Argentina" },
  "Raphaël Varane": { country: "Francia", nationalTeam: "France" },
  "Diogo Dalot": { country: "Portugal", nationalTeam: "Portugal" },
  "Bruno Fernandes": { country: "Portugal", nationalTeam: "Portugal" },
  "Kobbie Mainoo": { country: "Inglaterra", nationalTeam: "England" },
  "Mason Mount": { country: "Inglaterra", nationalTeam: "England" },
  "Rasmus Højlund": { country: "Dinamarca", nationalTeam: "Denmark" },
  "Alejandro Garnacho": { country: "Argentina", nationalTeam: "Argentina" },
  "Amad Diallo": { country: "Costa de Marfil", nationalTeam: "Ivory Coast" },
  "Casemiro": { country: "Brasil", nationalTeam: "Brazil" },
  "Manuel Ugarte": { country: "Uruguay", nationalTeam: "Uruguay" },
  "Senne Lammens": { country: "Bélgica", nationalTeam: "Belgium" },
  "Emiliano Martínez": { country: "Argentina", nationalTeam: "Argentina" },
  "Pau Torres": { country: "España", nationalTeam: "Spain" },
  "Lucas Digne": { country: "Francia", nationalTeam: "France" },
  "Youri Tielemans": { country: "Bélgica", nationalTeam: "Belgium" },
  "John McGinn": { country: "Escocia", nationalTeam: "Scotland" },
  "Douglas Luiz": { country: "Brasil", nationalTeam: "Brazil" },
  "Leon Bailey": { country: "Jamaica", nationalTeam: "Jamaica" },
  "Jhon Durán": { country: "Colombia", nationalTeam: "Colombia" },
  "Ian Maatsen": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Diego Carlos": { country: "Brasil", nationalTeam: "Brazil" },
  "Boubacar Kamara": { country: "Francia", nationalTeam: "France" },
  "Emile Smith Rowe": { country: "Inglaterra", nationalTeam: "England" },
  "Alisson Becker": { country: "Brasil", nationalTeam: "Brazil" },
  "Virgil van Dijk": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Ibrahima Konaté": { country: "Francia", nationalTeam: "France" },
  "Trent Alexander-Arnold": { country: "Inglaterra", nationalTeam: "England" },
  "Andy Robertson": { country: "Escocia", nationalTeam: "Scotland" },
  "Dominik Szoboszlai": { country: "Hungría", nationalTeam: "Hungary" },
  "Alexis Mac Allister": { country: "Argentina", nationalTeam: "Argentina" },
  "Ryan Gravenberch": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Mohamed Salah": { country: "Egipto", nationalTeam: "Egypt" },
  "Darwin Núñez": { country: "Uruguay", nationalTeam: "Uruguay" },
  "Luis Díaz": { country: "Colombia", nationalTeam: "Colombia" },
  "Cody Gakpo": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Wataru Endō": { country: "Japón", nationalTeam: "Japan" },
  "Jarell Quansah": { country: "Inglaterra", nationalTeam: "England" },
  "Ilya Zabarnyi": { country: "Ucrania", nationalTeam: "Ukraine" },
  "Marcos Senesi": { country: "Argentina", nationalTeam: "Argentina" },
  "Milos Kerkez": { country: "Hungría", nationalTeam: "Hungary" },
  "Tyler Adams": { country: "EE.UU.", nationalTeam: "USA" },
  "Alex Scott": { country: "Inglaterra", nationalTeam: "England" },
  "Antoine Semenyo": { country: "Ghana", nationalTeam: "Ghana" },
  "Eli Junior Kroupi": { country: "Francia", nationalTeam: "France" },
  "Justin Kluivert": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Dango Ouattara": { country: "Burkina Faso", nationalTeam: "Burkina Faso" },
  "Luis Sinisterra": { country: "Colombia", nationalTeam: "Colombia" },
  "Bart Verbruggen": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Jan Paul van Hecke": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Joël Veltman": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Pervis Estupiñán": { country: "Ecuador", nationalTeam: "Ecuador" },
  "Carlos Baleba": { country: "Camerún", nationalTeam: "Cameroon" },
  "Yankuba Minteh": { country: "Gambia", nationalTeam: "Gambia" },
  "Danny Welbeck": { country: "Inglaterra", nationalTeam: "England" },
  "Kaoru Mitoma": { country: "Japón", nationalTeam: "Japan" },
  "Evan Ferguson": { country: "Irlanda", nationalTeam: "Ireland" },
  "Matt O'Riley": { country: "Dinamarca", nationalTeam: "Denmark" },
  "Mark Flekken": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Nathan Collins": { country: "Irlanda", nationalTeam: "Ireland" },
  "Ethan Pinnock": { country: "Jamaica", nationalTeam: "Jamaica" },
  "Rico Henry": { country: "Inglaterra", nationalTeam: "England" },
  "Kristoffer Ajer": { country: "Noruega", nationalTeam: "Norway" },
  "Christian Nørgaard": { country: "Dinamarca", nationalTeam: "Denmark" },
  "Vitaly Janelt": { country: "Alemania", nationalTeam: "Germany" },
  "Mathias Jensen": { country: "Dinamarca", nationalTeam: "Denmark" },
  "Bryan Mbeumo": { country: "Camerún", nationalTeam: "Cameroon" },
  "Igor Thiago": { country: "Brasil", nationalTeam: "Brazil" },
  "Kevin Schade": { country: "Alemania", nationalTeam: "Germany" },
  "Frank Onyeka": { country: "Nigeria", nationalTeam: "Nigeria" },
  "Caoimhín Kelleher": { country: "Irlanda", nationalTeam: "Ireland" },
  "Robert Sánchez": { country: "España", nationalTeam: "Spain" },
  "Levi Colwill": { country: "Inglaterra", nationalTeam: "England" },
  "Wesley Fofana": { country: "Francia", nationalTeam: "France" },
  "Malo Gusto": { country: "Francia", nationalTeam: "France" },
  "Cole Palmer": { country: "Inglaterra", nationalTeam: "England" },
  "Enzo Fernández": { country: "Argentina", nationalTeam: "Argentina" },
  "Moises Caicedo": { country: "Ecuador", nationalTeam: "Ecuador" },
  "Nicolas Jackson": { country: "Senegal", nationalTeam: "Senegal" },
  "Mykhailo Mudryk": { country: "Ucrania", nationalTeam: "Ukraine" },
  "Romeo Lavia": { country: "Bélgica", nationalTeam: "Belgium" },
  "Noni Madueke": { country: "Inglaterra", nationalTeam: "England" },
  "Christopher Nkunku": { country: "Francia", nationalTeam: "France" },
  "Raheem Sterling": { country: "Inglaterra", nationalTeam: "England" },
  "Bernd Leno": { country: "Alemania", nationalTeam: "Germany" },
  "Joachim Andersen": { country: "Dinamarca", nationalTeam: "Denmark" },
  "Calvin Bassey": { country: "Nigeria", nationalTeam: "Nigeria" },
  "Antonee Robinson": { country: "EE.UU.", nationalTeam: "USA" },
  "Sander Berge": { country: "Noruega", nationalTeam: "Norway" },
  "Andreas Pereira": { country: "Brasil", nationalTeam: "Brazil" },
  "Raúl Jiménez": { country: "México", nationalTeam: "Mexico" },
  "Rodrigo Muniz": { country: "Brasil", nationalTeam: "Brazil" },
  "Harry Wilson": { country: "Gales", nationalTeam: "Wales" },
  "Alex Iwobi": { country: "Nigeria", nationalTeam: "Nigeria" },
  "Fabian Schär": { country: "Suiza", nationalTeam: "Switzerland" },
  "Sven Botman": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Kieran Trippier": { country: "Inglaterra", nationalTeam: "England" },
  "Joelinton": { country: "Brasil", nationalTeam: "Brazil" },
  "Bruno Guimarães": { country: "Brasil", nationalTeam: "Brazil" },
  "Sandro Tonali": { country: "Italia", nationalTeam: "Italy" },
  "Alexander Isak": { country: "Suecia", nationalTeam: "Sweden" },
  "Anthony Gordon": { country: "Inglaterra", nationalTeam: "England" },
  "Harvey Barnes": { country: "Inglaterra", nationalTeam: "England" },
  "Miguel Almirón": { country: "Paraguay", nationalTeam: "Paraguay" },
  "Elliot Anderson": { country: "Escocia", nationalTeam: "Scotland" },
  "Callum Wilson": { country: "Inglaterra", nationalTeam: "England" },
  "Tino Livramento": { country: "Inglaterra", nationalTeam: "England" },
  "Jordan Pickford": { country: "Inglaterra", nationalTeam: "England" },
  "Jarrad Branthwaite": { country: "Inglaterra", nationalTeam: "England" },
  "Vitalii Mykolenko": { country: "Ucrania", nationalTeam: "Ukraine" },
  "Amadou Onana": { country: "Bélgica", nationalTeam: "Belgium" },
  "Abdoulaye Doucouré": { country: "Mali", nationalTeam: "Mali" },
  "Dwight McNeil": { country: "Inglaterra", nationalTeam: "England" },
  "Dominic Calvert-Lewin": { country: "Inglaterra", nationalTeam: "England" },
  "Iliman Ndiaye": { country: "Senegal", nationalTeam: "Senegal" },
  "Jesper Lindstrøm": { country: "Dinamarca", nationalTeam: "Denmark" },
  "Crysencio Summerville": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Ethan Ampadu": { country: "Gales", nationalTeam: "Wales" },
  "Glen Kamara": { country: "Finlandia", nationalTeam: "Finland" },
  "Wilfried Gnonto": { country: "Italia", nationalTeam: "Italy" },
  "Georginio Rutter": { country: "Francia", nationalTeam: "France" },
  "Joel Piroe": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Max Wöber": { country: "Austria", nationalTeam: "Austria" },
  "Dean Henderson": { country: "Inglaterra", nationalTeam: "England" },
  "Marc Guéhi": { country: "Inglaterra", nationalTeam: "England" },
  "Daniel Muñoz": { country: "Colombia", nationalTeam: "Colombia" },
  "Jefferson Lerma": { country: "Colombia", nationalTeam: "Colombia" },
  "Adam Wharton": { country: "Inglaterra", nationalTeam: "England" },
  "Eberechi Eze": { country: "Nigeria", nationalTeam: "Nigeria" },
  "Michael Olise": { country: "Francia", nationalTeam: "France" },
  "Jean-Philippe Mateta": { country: "Francia", nationalTeam: "France" },
  "Odsonne Edouard": { country: "Francia", nationalTeam: "France" },
  "Cheick Doucouré": { country: "Mali", nationalTeam: "Mali" },
  "Jordan Ayew": { country: "Ghana", nationalTeam: "Ghana" },
  "Chris Richards": { country: "EE.UU.", nationalTeam: "USA" },
  "Murillo": { country: "Brasil", nationalTeam: "Brazil" },
  "Neco Williams": { country: "Gales", nationalTeam: "Wales" },
  "Ola Aina": { country: "Nigeria", nationalTeam: "Nigeria" },
  "Ibrahim Sangaré": { country: "Costa de Marfil", nationalTeam: "Ivory Coast" },
  "Morgan Gibbs-White": { country: "Inglaterra", nationalTeam: "England" },
  "Anthony Elanga": { country: "Suecia", nationalTeam: "Sweden" },
  "Taiwo Awoniyi": { country: "Nigeria", nationalTeam: "Nigeria" },
  "Chris Wood": { country: "Nueva Zelanda", nationalTeam: "New Zealand" },
  "Callum Hudson-Odoi": { country: "Inglaterra", nationalTeam: "England" },
  "Danilo": { country: "Brasil", nationalTeam: "Brazil" },
  "Nicolas Dominguez": { country: "Italia", nationalTeam: "Italy" },
  "Andrew Omobamidele": { country: "Irlanda", nationalTeam: "Ireland" },
  "Guglielmo Vicario": { country: "Italia", nationalTeam: "Italy" },
  "Cristian Romero": { country: "Argentina", nationalTeam: "Argentina" },
  "Micky van de Ven": { country: "Países Bajos", nationalTeam: "Netherlands" },
  "Pedro Porro": { country: "España", nationalTeam: "Spain" },
  "Destiny Udogie": { country: "Italia", nationalTeam: "Italy" },
  "James Maddison": { country: "Inglaterra", nationalTeam: "England" },
  "Yves Bissouma": { country: "Mali", nationalTeam: "Mali" },
  "Pape Matar Sarr": { country: "Senegal", nationalTeam: "Senegal" },
  "Dejan Kulusevski": { country: "Suecia", nationalTeam: "Sweden" },
  "Heung-min Son": { country: "Corea del Sur", nationalTeam: "South Korea" },
  "Richarlison": { country: "Brasil", nationalTeam: "Brazil" },
  "Brennan Johnson": { country: "Gales", nationalTeam: "Wales" },
  "Rodrigo Bentancur": { country: "Uruguay", nationalTeam: "Uruguay" },
  "Radu Drăgușin": { country: "Rumanía", nationalTeam: "Romania" },
  "Timo Werner": { country: "Alemania", nationalTeam: "Germany" },
  "Alphonse Areola": { country: "Francia", nationalTeam: "France" },
  "Kurt Zouma": { country: "Francia", nationalTeam: "France" },
  "Nayef Aguerd": { country: "Marruecos", nationalTeam: "Morocco" },
  "Emerson Palmieri": { country: "Italia", nationalTeam: "Italy" },
  "Vladimír Coufal": { country: "República Checa", nationalTeam: "Czech Republic" },
  "Lucas Paquetá": { country: "Brasil", nationalTeam: "Brazil" },
  "Edson Álvarez": { country: "México", nationalTeam: "Mexico" },
  "James Ward-Prowse": { country: "Inglaterra", nationalTeam: "England" },
  "Jarrod Bowen": { country: "Inglaterra", nationalTeam: "England" },
  "Mohammed Kudus": { country: "Ghana", nationalTeam: "Ghana" },
  "Niklas Füllkrug": { country: "Alemania", nationalTeam: "Germany" },
  "Tomáš Souček": { country: "República Checa", nationalTeam: "Czech Republic" },
  "Aaron Wan-Bissaka": { country: "Inglaterra", nationalTeam: "England" },
  "Maxwel Cornet": { country: "Costa de Marfil", nationalTeam: "Ivory Coast" },
  "Danny Ings": { country: "Inglaterra", nationalTeam: "England" },
  "James Trafford": { country: "Inglaterra", nationalTeam: "England" },
  "Dara O'Shea": { country: "Irlanda", nationalTeam: "Ireland" },
  "Jordan Beyer": { country: "Alemania", nationalTeam: "Germany" },
  "Josh Cullen": { country: "Irlanda", nationalTeam: "Ireland" },
  "Lyle Foster": { country: "Sudáfrica", nationalTeam: "South Africa" },
  "Zeki Amdouni": { country: "Suiza", nationalTeam: "Switzerland" },
  "Hannibal Mejbri": { country: "Túnez", nationalTeam: "Tunisia" },
  "Luca Koleosho": { country: "Italia", nationalTeam: "Italy" },
  "José Sá": { country: "Portugal", nationalTeam: "Portugal" },
  "Max Kilman": { country: "Inglaterra", nationalTeam: "England" },
  "Rayan Aït-Nouri": { country: "Argelia", nationalTeam: "Algeria" },
  "Nélson Semedo": { country: "Portugal", nationalTeam: "Portugal" },
  "João Gomes": { country: "Brasil", nationalTeam: "Brazil" },
  "Mario Lemina": { country: "Gabón", nationalTeam: "Gabon" },
  "Jean-Ricner Bellegarde": { country: "Francia", nationalTeam: "France" },
  "Matheus Cunha": { country: "Brasil", nationalTeam: "Brazil" },
  "Hwang Hee-chan": { country: "Corea del Sur", nationalTeam: "South Korea" },
  "Pablo Sarabia": { country: "España", nationalTeam: "Spain" },
  "Tommy Doyle": { country: "Inglaterra", nationalTeam: "England" },
  "Fabio Silva": { country: "Portugal", nationalTeam: "Portugal" },
  "Jadon Sancho": { country: "Inglaterra", nationalTeam: "England" },
  "Jobe Bellingham": { country: "Inglaterra", nationalTeam: "England" },
  "Eliezer Mayenda": { country: "España", nationalTeam: "Spain" },
  "Abdoullah Ba": { country: "Francia", nationalTeam: "France" },
  "Adil Aouchiche": { country: "Francia", nationalTeam: "France" },
};

export function getPlayerNationality(name: string, leagueCountry: string): { country: string; nationalTeam: string } {
  const map = leagueCountry === "España" ? NOT_SPANISH : NOT_ENGLISH;
  const entry = map[name];
  if (entry) return entry;
  // Default: player nationality matches league country
  const ntName = leagueCountry === "España" ? "Spain" : "England";
  return { country: leagueCountry, nationalTeam: ntName };
}
