import type { LigaTeamData } from "./liga-data";

const R = (a: number, c: number, d: number) => ({
  attack: a, control: c, defense: d, total: Math.round((a + c + d) / 3)
});

export const PREMIER_TEAMS: LigaTeamData[] = [
  {
    name: "Arsenal", shortName: "ARS", country: "Inglaterra",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "David Raya", position: "GK", ...R(25, 62, 94), rarity: "LEGENDARY", rating: 7.6 },
      { name: "William Saliba", position: "DEF", ...R(45, 72, 92), rarity: "LEGENDARY", rating: 7.5 },
      { name: "Gabriel", position: "DEF", ...R(40, 68, 90), rarity: "EPIC", rating: 7.4 },
      { name: "Jurriën Timber", position: "DEF", ...R(60, 76, 86), rarity: "EPIC", rating: 7.3 },
      { name: "Ben White", position: "DEF", ...R(55, 74, 84), rarity: "EPIC", rating: 7.2 },
      { name: "Declan Rice", position: "MID", ...R(68, 85, 82), rarity: "LEGENDARY", goals: 6, assists: 5, rating: 7.5 },
      { name: "Martin Ødegaard", position: "MID", ...R(78, 90, 50), rarity: "GOLDEN", goals: 8, assists: 7, rating: 7.6 },
      { name: "Viktor Gyökeres", position: "FWD", ...R(88, 72, 30), rarity: "GOLDEN", goals: 14, assists: 5, rating: 7.5 },
      { name: "Bukayo Saka", position: "FWD", ...R(88, 82, 35), rarity: "LEGENDARY", goals: 10, assists: 8, rating: 7.6 },
      { name: "Gabriel Martinelli", position: "FWD", ...R(84, 76, 30), rarity: "EPIC", goals: 8, assists: 6, rating: 7.3 },
      { name: "Kai Havertz", position: "MID", ...R(78, 78, 48), rarity: "EPIC", goals: 7, assists: 5, rating: 7.2 },
      { name: "Mikel Merino", position: "MID", ...R(72, 80, 62), rarity: "EPIC", rating: 7.2 },
      { name: "Leandro Trossard", position: "FWD", ...R(80, 76, 30), rarity: "RARE", rating: 7.1 },
      { name: "Riccardo Calafiori", position: "DEF", ...R(55, 72, 82), rarity: "RARE", rating: 7.0 },
      { name: "Thomas Partey", position: "MID", ...R(55, 78, 65), rarity: "RARE", rating: 7.0 },
      { name: "Martin Zubimendi", position: "MID", ...R(55, 85, 68), rarity: "EPIC", rating: 7.3 },
    ],
  },
  {
    name: "Manchester City", shortName: "MCI", country: "Inglaterra",
    colors: { primary: "#6cabdd", secondary: "#ffffff", accent: "#c8102e" },
    players: [
      { name: "Gianluigi Donnarumma", position: "GK", ...R(25, 58, 92), rarity: "LEGENDARY", rating: 7.5 },
      { name: "Rúben Dias", position: "DEF", ...R(40, 70, 90), rarity: "LEGENDARY", rating: 7.4 },
      { name: "John Stones", position: "DEF", ...R(55, 80, 88), rarity: "EPIC", rating: 7.3 },
      { name: "Josko Gvardiol", position: "DEF", ...R(60, 76, 86), rarity: "EPIC", rating: 7.3 },
      { name: "Kyle Walker", position: "DEF", ...R(60, 72, 82), rarity: "RARE", rating: 7.0 },
      { name: "Rodri", position: "MID", ...R(65, 88, 82), rarity: "LEGENDARY", goals: 5, assists: 6, rating: 7.6 },
      { name: "Kevin De Bruyne", position: "MID", ...R(88, 92, 45), rarity: "ULTRA_RARE", goals: 8, assists: 9, rating: 7.7 },
      { name: "Phil Foden", position: "MID", ...R(86, 88, 40), rarity: "GOLDEN", goals: 10, assists: 7, rating: 7.6 },
      { name: "Erling Haaland", position: "FWD", ...R(99, 70, 30), rarity: "ULTRA_RARE", goals: 27, assists: 4, rating: 8.1 },
      { name: "Jérémy Doku", position: "FWD", ...R(84, 74, 28), rarity: "EPIC", goals: 6, assists: 7, rating: 7.2 },
      { name: "Bernardo Silva", position: "MID", ...R(72, 88, 55), rarity: "LEGENDARY", rating: 7.4 },
      { name: "Matheus Nunes", position: "MID", ...R(65, 78, 50), rarity: "RARE", rating: 7.0 },
      { name: "Nico O'Reilly", position: "DEF", ...R(55, 72, 80), rarity: "RARE", rating: 7.1 },
      { name: "Rico Lewis", position: "DEF", ...R(58, 74, 78), rarity: "RARE", rating: 7.0 },
      { name: "Jack Grealish", position: "FWD", ...R(78, 80, 30), rarity: "EPIC", rating: 7.2 },
      { name: "Sávio", position: "FWD", ...R(76, 72, 25), rarity: "RARE", rating: 7.0 },
    ],
  },
  {
    name: "Manchester United", shortName: "MUN", country: "Inglaterra",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "André Onana", position: "GK", ...R(28, 62, 86), rarity: "EPIC", rating: 7.2 },
      { name: "Lisandro Martínez", position: "DEF", ...R(45, 72, 86), rarity: "EPIC", rating: 7.3 },
      { name: "Raphaël Varane", position: "DEF", ...R(40, 68, 88), rarity: "EPIC", rating: 7.2 },
      { name: "Diogo Dalot", position: "DEF", ...R(55, 72, 80), rarity: "RARE", rating: 7.0 },
      { name: "Luke Shaw", position: "DEF", ...R(58, 74, 82), rarity: "RARE", rating: 7.1 },
      { name: "Bruno Fernandes", position: "MID", ...R(86, 88, 48), rarity: "GOLDEN", goals: 12, assists: 8, rating: 7.7 },
      { name: "Kobbie Mainoo", position: "MID", ...R(62, 82, 60), rarity: "EPIC", rating: 7.3 },
      { name: "Mason Mount", position: "MID", ...R(76, 80, 45), rarity: "RARE", rating: 7.1 },
      { name: "Marcus Rashford", position: "FWD", ...R(86, 76, 30), rarity: "GOLDEN", goals: 11, assists: 6, rating: 7.4 },
      { name: "Rasmus Højlund", position: "FWD", ...R(82, 68, 28), rarity: "EPIC", goals: 9, assists: 4, rating: 7.2 },
      { name: "Alejandro Garnacho", position: "FWD", ...R(82, 74, 28), rarity: "EPIC", goals: 7, assists: 5, rating: 7.2 },
      { name: "Amad Diallo", position: "FWD", ...R(76, 74, 30), rarity: "RARE", rating: 7.0 },
      { name: "Casemiro", position: "MID", ...R(50, 76, 72), rarity: "RARE", rating: 7.0 },
      { name: "Harry Maguire", position: "DEF", ...R(40, 65, 82), rarity: "RARE", rating: 6.9 },
      { name: "Senne Lammens", position: "GK", ...R(25, 58, 82), rarity: "RARE", rating: 7.0 },
      { name: "Manuel Ugarte", position: "MID", ...R(50, 74, 70), rarity: "RARE", rating: 7.0 },
    ],
  },
  {
    name: "Aston Villa", shortName: "AVL", country: "Inglaterra",
    colors: { primary: "#670e36", secondary: "#95bfe5", accent: "#ffcc00" },
    players: [
      { name: "Emiliano Martínez", position: "GK", ...R(28, 60, 90), rarity: "LEGENDARY", rating: 7.4 },
      { name: "Pau Torres", position: "DEF", ...R(45, 72, 86), rarity: "EPIC", rating: 7.2 },
      { name: "Ezri Konsa", position: "DEF", ...R(40, 68, 84), rarity: "RARE", rating: 7.1 },
      { name: "Lucas Digne", position: "DEF", ...R(55, 72, 80), rarity: "RARE", rating: 7.0 },
      { name: "Matty Cash", position: "DEF", ...R(58, 68, 78), rarity: "RARE", rating: 6.9 },
      { name: "Youri Tielemans", position: "MID", ...R(65, 82, 55), rarity: "EPIC", rating: 7.2 },
      { name: "John McGinn", position: "MID", ...R(72, 80, 55), rarity: "EPIC", goals: 5, assists: 6, rating: 7.3 },
      { name: "Douglas Luiz", position: "MID", ...R(62, 84, 60), rarity: "EPIC", rating: 7.3 },
      { name: "Ollie Watkins", position: "FWD", ...R(88, 72, 30), rarity: "GOLDEN", goals: 16, assists: 6, rating: 7.5 },
      { name: "Leon Bailey", position: "FWD", ...R(80, 74, 28), rarity: "EPIC", goals: 6, assists: 5, rating: 7.1 },
      { name: "Jhon Durán", position: "FWD", ...R(78, 62, 25), rarity: "RARE", goals: 5, assists: 2, rating: 6.9 },
      { name: "Morgan Rogers", position: "MID", ...R(68, 74, 40), rarity: "RARE", rating: 7.0 },
      { name: "Ian Maatsen", position: "DEF", ...R(55, 72, 76), rarity: "RARE", rating: 6.9 },
      { name: "Diego Carlos", position: "DEF", ...R(35, 62, 80), rarity: "RARE", rating: 6.9 },
      { name: "Boubacar Kamara", position: "MID", ...R(50, 76, 65), rarity: "RARE", rating: 7.0 },
      { name: "Jaden Philogene", position: "FWD", ...R(72, 68, 25), rarity: "BASE", rating: 6.8 },
    ],
  },
  {
    name: "Liverpool", shortName: "LIV", country: "Inglaterra",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Alisson Becker", position: "GK", ...R(25, 60, 92), rarity: "LEGENDARY", rating: 7.5 },
      { name: "Virgil van Dijk", position: "DEF", ...R(50, 76, 92), rarity: "LEGENDARY", rating: 7.5 },
      { name: "Ibrahima Konaté", position: "DEF", ...R(45, 68, 88), rarity: "EPIC", rating: 7.3 },
      { name: "Trent Alexander-Arnold", position: "DEF", ...R(82, 88, 72), rarity: "GOLDEN", rating: 7.5 },
      { name: "Andy Robertson", position: "DEF", ...R(60, 78, 80), rarity: "EPIC", rating: 7.2 },
      { name: "Dominik Szoboszlai", position: "MID", ...R(82, 86, 50), rarity: "GOLDEN", goals: 8, assists: 7, rating: 7.5 },
      { name: "Alexis Mac Allister", position: "MID", ...R(72, 86, 58), rarity: "EPIC", rating: 7.4 },
      { name: "Ryan Gravenberch", position: "MID", ...R(65, 82, 55), rarity: "EPIC", rating: 7.2 },
      { name: "Mohamed Salah", position: "FWD", ...R(94, 82, 30), rarity: "ULTRA_RARE", goals: 12, assists: 8, rating: 7.7 },
      { name: "Darwin Núñez", position: "FWD", ...R(84, 65, 28), rarity: "EPIC", goals: 9, assists: 5, rating: 7.2 },
      { name: "Luis Díaz", position: "FWD", ...R(86, 78, 30), rarity: "EPIC", goals: 7, assists: 6, rating: 7.3 },
      { name: "Cody Gakpo", position: "FWD", ...R(80, 76, 30), rarity: "RARE", rating: 7.1 },
      { name: "Curtis Jones", position: "MID", ...R(62, 78, 50), rarity: "RARE", rating: 7.0 },
      { name: "Wataru Endō", position: "MID", ...R(45, 72, 68), rarity: "RARE", rating: 7.0 },
      { name: "Jarell Quansah", position: "DEF", ...R(40, 65, 80), rarity: "RARE", rating: 6.9 },
      { name: "Conor Bradley", position: "DEF", ...R(55, 68, 78), rarity: "RARE", rating: 6.9 },
    ],
  },
  {
    name: "Bournemouth", shortName: "BOU", country: "Inglaterra",
    colors: { primary: "#c8102e", secondary: "#000000", accent: "#ffffff" },
    players: [
      { name: "Đorđe Petrović", position: "GK", ...R(28, 58, 84), rarity: "RARE", rating: 7.1 },
      { name: "Ilya Zabarnyi", position: "DEF", ...R(40, 65, 82), rarity: "RARE", rating: 7.0 },
      { name: "Marcos Senesi", position: "DEF", ...R(50, 72, 80), rarity: "RARE", rating: 7.0 },
      { name: "Milos Kerkez", position: "DEF", ...R(58, 72, 78), rarity: "RARE", rating: 7.0 },
      { name: "Adam Smith", position: "DEF", ...R(45, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Tyler Adams", position: "MID", ...R(50, 74, 68), rarity: "RARE", rating: 7.0 },
      { name: "Alex Scott", position: "MID", ...R(62, 78, 48), rarity: "RARE", rating: 7.1 },
      { name: "Antoine Semenyo", position: "FWD", ...R(84, 74, 30), rarity: "GOLDEN", goals: 17, assists: 5, rating: 7.5 },
      { name: "Eli Junior Kroupi", position: "FWD", ...R(78, 72, 25), rarity: "EPIC", goals: 13, assists: 4, rating: 7.3 },
      { name: "Justin Kluivert", position: "FWD", ...R(76, 72, 28), rarity: "RARE", goals: 6, assists: 5, rating: 7.0 },
      { name: "Dango Ouattara", position: "FWD", ...R(74, 68, 25), rarity: "RARE", rating: 6.9 },
      { name: "Ryan Christie", position: "MID", ...R(55, 74, 52), rarity: "BASE", rating: 6.8 },
      { name: "Lewis Cook", position: "MID", ...R(50, 76, 58), rarity: "RARE", rating: 6.9 },
      { name: "Luis Sinisterra", position: "FWD", ...R(74, 72, 28), rarity: "RARE", rating: 7.0 },
      { name: "James Hill", position: "DEF", ...R(35, 60, 76), rarity: "BASE", rating: 6.6 },
      { name: "Max Aarons", position: "DEF", ...R(50, 65, 76), rarity: "RARE", rating: 6.8 },
    ],
  },
  {
    name: "Sunderland", shortName: "SUN", country: "Inglaterra",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Robin Roefs", position: "GK", ...R(25, 56, 82), rarity: "RARE", rating: 6.9 },
      { name: "Daniel Ballard", position: "DEF", ...R(40, 62, 80), rarity: "RARE", rating: 6.8 },
      { name: "Luke O'Nien", position: "DEF", ...R(45, 62, 78), rarity: "BASE", rating: 6.7 },
      { name: "Trai Hume", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Dennis Cirkin", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Dan Neil", position: "MID", ...R(55, 76, 55), rarity: "RARE", rating: 6.9 },
      { name: "Chris Rigg", position: "MID", ...R(58, 72, 48), rarity: "RARE", rating: 6.9 },
      { name: "Jobe Bellingham", position: "MID", ...R(65, 74, 50), rarity: "RARE", rating: 7.0 },
      { name: "Patrick Roberts", position: "FWD", ...R(72, 70, 28), rarity: "RARE", rating: 6.9 },
      { name: "Jack Clarke", position: "FWD", ...R(76, 70, 25), rarity: "RARE", goals: 8, assists: 4, rating: 7.1 },
      { name: "Nazariy Rusyn", position: "FWD", ...R(70, 62, 22), rarity: "BASE", rating: 6.7 },
      { name: "Eliezer Mayenda", position: "FWD", ...R(68, 62, 22), rarity: "BASE", rating: 6.6 },
      { name: "Abdoullah Ba", position: "MID", ...R(58, 68, 42), rarity: "BASE", rating: 6.6 },
      { name: "Niall Huggins", position: "DEF", ...R(48, 62, 74), rarity: "BASE", rating: 6.5 },
      { name: "Adil Aouchiche", position: "MID", ...R(62, 72, 38), rarity: "BASE", rating: 6.7 },
      { name: "Milan Aleksić", position: "MID", ...R(55, 68, 45), rarity: "BASE", rating: 6.6 },
    ],
  },
  {
    name: "Brighton & Hove Albion", shortName: "BRI", country: "Inglaterra",
    colors: { primary: "#005dbb", secondary: "#ffffff", accent: "#ffcc00" },
    players: [
      { name: "Bart Verbruggen", position: "GK", ...R(28, 60, 86), rarity: "EPIC", rating: 7.2 },
      { name: "Lewis Dunk", position: "DEF", ...R(40, 68, 86), rarity: "EPIC", rating: 7.1 },
      { name: "Jan Paul van Hecke", position: "DEF", ...R(40, 65, 82), rarity: "RARE", rating: 7.0 },
      { name: "Joël Veltman", position: "DEF", ...R(45, 68, 80), rarity: "RARE", rating: 6.9 },
      { name: "Pervis Estupiñán", position: "DEF", ...R(60, 74, 78), rarity: "EPIC", rating: 7.1 },
      { name: "Carlos Baleba", position: "MID", ...R(58, 76, 62), rarity: "RARE", rating: 7.0 },
      { name: "Yankuba Minteh", position: "FWD", ...R(78, 72, 28), rarity: "RARE", rating: 7.0 },
      { name: "João Pedro", position: "FWD", ...R(82, 76, 35), rarity: "EPIC", goals: 7, assists: 5, rating: 7.2 },
      { name: "Danny Welbeck", position: "FWD", ...R(76, 72, 32), rarity: "RARE", goals: 13, assists: 4, rating: 7.2 },
      { name: "Kaoru Mitoma", position: "FWD", ...R(86, 78, 30), rarity: "EPIC", goals: 6, assists: 6, rating: 7.3 },
      { name: "Evan Ferguson", position: "FWD", ...R(78, 68, 25), rarity: "RARE", rating: 6.9 },
      { name: "James Milner", position: "MID", ...R(55, 78, 60), rarity: "RARE", rating: 7.0 },
      { name: "Adam Webster", position: "DEF", ...R(35, 65, 80), rarity: "RARE", rating: 6.9 },
      { name: "Tariq Lamptey", position: "DEF", ...R(58, 70, 74), rarity: "RARE", rating: 6.8 },
      { name: "Solomon March", position: "MID", ...R(65, 74, 45), rarity: "RARE", rating: 6.9 },
      { name: "Matt O'Riley", position: "MID", ...R(65, 78, 45), rarity: "RARE", rating: 7.0 },
    ],
  },
  {
    name: "Brentford", shortName: "BRE", country: "Inglaterra",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Mark Flekken", position: "GK", ...R(28, 60, 84), rarity: "RARE", rating: 7.0 },
      { name: "Nathan Collins", position: "DEF", ...R(40, 65, 82), rarity: "RARE", rating: 7.0 },
      { name: "Ethan Pinnock", position: "DEF", ...R(35, 62, 80), rarity: "RARE", rating: 6.9 },
      { name: "Rico Henry", position: "DEF", ...R(55, 72, 80), rarity: "RARE", rating: 7.0 },
      { name: "Kristoffer Ajer", position: "DEF", ...R(45, 68, 80), rarity: "RARE", rating: 6.9 },
      { name: "Christian Nørgaard", position: "MID", ...R(50, 78, 65), rarity: "RARE", rating: 7.0 },
      { name: "Vitaly Janelt", position: "MID", ...R(55, 76, 60), rarity: "RARE", rating: 6.9 },
      { name: "Mathias Jensen", position: "MID", ...R(60, 80, 50), rarity: "RARE", rating: 7.0 },
      { name: "Bryan Mbeumo", position: "FWD", ...R(82, 74, 30), rarity: "EPIC", goals: 8, assists: 5, rating: 7.2 },
      { name: "Igor Thiago", position: "FWD", ...R(86, 68, 28), rarity: "GOLDEN", goals: 22, assists: 4, rating: 7.6 },
      { name: "Kevin Schade", position: "FWD", ...R(76, 70, 28), rarity: "RARE", goals: 6, assists: 3, rating: 7.0 },
      { name: "Keane Lewis-Potter", position: "FWD", ...R(72, 68, 25), rarity: "BASE", rating: 6.8 },
      { name: "Mads Roerslev", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Frank Onyeka", position: "MID", ...R(55, 72, 58), rarity: "BASE", rating: 6.7 },
      { name: "Caoimhín Kelleher", position: "GK", ...R(25, 58, 84), rarity: "RARE", rating: 7.0 },
      { name: "Saman Ghoddos", position: "MID", ...R(58, 72, 42), rarity: "BASE", rating: 6.7 },
    ],
  },
  {
    name: "Chelsea", shortName: "CHE", country: "Inglaterra",
    colors: { primary: "#005dbb", secondary: "#ffffff", accent: "#c8102e" },
    players: [
      { name: "Robert Sánchez", position: "GK", ...R(28, 58, 84), rarity: "RARE", rating: 7.0 },
      { name: "Levi Colwill", position: "DEF", ...R(45, 70, 84), rarity: "EPIC", rating: 7.1 },
      { name: "Wesley Fofana", position: "DEF", ...R(40, 65, 84), rarity: "RARE", rating: 7.0 },
      { name: "Reece James", position: "DEF", ...R(65, 78, 82), rarity: "EPIC", rating: 7.2 },
      { name: "Malo Gusto", position: "DEF", ...R(58, 72, 78), rarity: "RARE", rating: 7.0 },
      { name: "Cole Palmer", position: "MID", ...R(86, 84, 40), rarity: "GOLDEN", goals: 9, assists: 7, rating: 7.5 },
      { name: "Enzo Fernández", position: "MID", ...R(68, 85, 58), rarity: "EPIC", rating: 7.3 },
      { name: "Moises Caicedo", position: "MID", ...R(55, 78, 72), rarity: "EPIC", rating: 7.2 },
      { name: "Raheem Sterling", position: "FWD", ...R(84, 76, 30), rarity: "EPIC", goals: 7, assists: 5, rating: 7.2 },
      { name: "Nicolas Jackson", position: "FWD", ...R(80, 68, 25), rarity: "RARE", goals: 8, assists: 4, rating: 7.0 },
      { name: "João Pedro", position: "FWD", ...R(82, 74, 30), rarity: "EPIC", goals: 15, assists: 5, rating: 7.4 },
      { name: "Mykhailo Mudryk", position: "FWD", ...R(78, 72, 25), rarity: "RARE", rating: 6.9 },
      { name: "Romeo Lavia", position: "MID", ...R(55, 76, 60), rarity: "RARE", rating: 7.0 },
      { name: "Ben Chilwell", position: "DEF", ...R(60, 76, 78), rarity: "EPIC", rating: 7.1 },
      { name: "Noni Madueke", position: "FWD", ...R(76, 72, 28), rarity: "RARE", rating: 7.0 },
      { name: "Christopher Nkunku", position: "FWD", ...R(82, 82, 35), rarity: "EPIC", rating: 7.3 },
    ],
  },
  {
    name: "Fulham", shortName: "FUL", country: "Inglaterra",
    colors: { primary: "#ffffff", secondary: "#000000", accent: "#c8102e" },
    players: [
      { name: "Bernd Leno", position: "GK", ...R(28, 60, 86), rarity: "EPIC", rating: 7.2 },
      { name: "Joachim Andersen", position: "DEF", ...R(40, 68, 84), rarity: "RARE", rating: 7.0 },
      { name: "Calvin Bassey", position: "DEF", ...R(35, 62, 80), rarity: "RARE", rating: 6.9 },
      { name: "Antonee Robinson", position: "DEF", ...R(58, 72, 78), rarity: "RARE", rating: 7.0 },
      { name: "Kenny Tete", position: "DEF", ...R(50, 65, 78), rarity: "BASE", rating: 6.8 },
      { name: "Sander Berge", position: "MID", ...R(55, 76, 62), rarity: "RARE", rating: 7.0 },
      { name: "Andreas Pereira", position: "MID", ...R(72, 82, 45), rarity: "EPIC", goals: 5, assists: 6, rating: 7.2 },
      { name: "Emile Smith Rowe", position: "MID", ...R(72, 78, 45), rarity: "RARE", rating: 7.0 },
      { name: "Alex Iwobi", position: "MID", ...R(68, 76, 48), rarity: "RARE", rating: 7.0 },
      { name: "Raúl Jiménez", position: "FWD", ...R(78, 68, 28), rarity: "RARE", goals: 7, assists: 3, rating: 7.0 },
      { name: "Harry Wilson", position: "FWD", ...R(74, 72, 30), rarity: "RARE", rating: 6.9 },
      { name: "Rodrigo Muniz", position: "FWD", ...R(74, 65, 25), rarity: "BASE", rating: 6.8 },
      { name: "Reiss Nelson", position: "FWD", ...R(72, 70, 25), rarity: "RARE", rating: 6.9 },
      { name: "Harrison Reed", position: "MID", ...R(50, 74, 58), rarity: "BASE", rating: 6.8 },
      { name: "Jorge Cuenca", position: "DEF", ...R(35, 62, 78), rarity: "BASE", rating: 6.7 },
      { name: "Tom Cairney", position: "MID", ...R(58, 78, 45), rarity: "RARE", rating: 7.0 },
    ],
  },
  {
    name: "Newcastle United", shortName: "NEW", country: "Inglaterra",
    colors: { primary: "#000000", secondary: "#ffffff", accent: "#c8102e" },
    players: [
      { name: "Nick Pope", position: "GK", ...R(28, 58, 86), rarity: "EPIC", rating: 7.1 },
      { name: "Fabian Schär", position: "DEF", ...R(45, 70, 84), rarity: "RARE", rating: 7.1 },
      { name: "Sven Botman", position: "DEF", ...R(40, 68, 86), rarity: "EPIC", rating: 7.2 },
      { name: "Kieran Trippier", position: "DEF", ...R(72, 82, 80), rarity: "LEGENDARY", rating: 7.3 },
      { name: "Dan Burn", position: "DEF", ...R(40, 62, 82), rarity: "RARE", rating: 6.9 },
      { name: "Bruno Guimarães", position: "MID", ...R(65, 85, 68), rarity: "EPIC", rating: 7.3 },
      { name: "Sandro Tonali", position: "MID", ...R(65, 82, 65), rarity: "EPIC", rating: 7.3 },
      { name: "Joelinton", position: "MID", ...R(72, 76, 60), rarity: "RARE", rating: 7.1 },
      { name: "Alexander Isak", position: "FWD", ...R(88, 78, 30), rarity: "GOLDEN", goals: 10, assists: 5, rating: 7.4 },
      { name: "Anthony Gordon", position: "FWD", ...R(82, 76, 30), rarity: "EPIC", goals: 7, assists: 5, rating: 7.2 },
      { name: "Harvey Barnes", position: "FWD", ...R(78, 74, 28), rarity: "RARE", rating: 7.0 },
      { name: "Miguel Almirón", position: "MID", ...R(72, 72, 45), rarity: "RARE", rating: 6.9 },
      { name: "Lewis Hall", position: "DEF", ...R(55, 72, 76), rarity: "RARE", rating: 6.9 },
      { name: "Elliot Anderson", position: "MID", ...R(62, 74, 42), rarity: "RARE", rating: 6.9 },
      { name: "Callum Wilson", position: "FWD", ...R(80, 65, 25), rarity: "RARE", rating: 7.0 },
      { name: "Tino Livramento", position: "DEF", ...R(55, 72, 78), rarity: "RARE", rating: 6.9 },
    ],
  },
  {
    name: "Everton", shortName: "EVE", country: "Inglaterra",
    colors: { primary: "#005dbb", secondary: "#ffffff", accent: "#ffcc00" },
    players: [
      { name: "Jordan Pickford", position: "GK", ...R(28, 62, 88), rarity: "LEGENDARY", rating: 7.4 },
      { name: "James Tarkowski", position: "DEF", ...R(35, 65, 84), rarity: "RARE", rating: 7.0 },
      { name: "Jarrad Branthwaite", position: "DEF", ...R(40, 68, 86), rarity: "EPIC", rating: 7.2 },
      { name: "Vitalii Mykolenko", position: "DEF", ...R(50, 68, 78), rarity: "RARE", rating: 6.9 },
      { name: "Coleman", position: "DEF", ...R(45, 65, 78), rarity: "RARE", rating: 6.8 },
      { name: "Amadou Onana", position: "MID", ...R(55, 78, 65), rarity: "EPIC", rating: 7.1 },
      { name: "James Garner", position: "MID", ...R(58, 76, 55), rarity: "RARE", rating: 7.0 },
      { name: "Abdoulaye Doucouré", position: "MID", ...R(65, 74, 55), rarity: "RARE", rating: 7.0 },
      { name: "Dwight McNeil", position: "FWD", ...R(76, 75, 35), rarity: "RARE", goals: 5, assists: 5, rating: 7.0 },
      { name: "Jack Grealish", position: "FWD", ...R(78, 80, 30), rarity: "EPIC", goals: 6, assists: 5, rating: 7.2 },
      { name: "Dominic Calvert-Lewin", position: "FWD", ...R(80, 65, 28), rarity: "EPIC", goals: 14, assists: 3, rating: 7.3 },
      { name: "Iliman Ndiaye", position: "FWD", ...R(76, 72, 28), rarity: "RARE", rating: 6.9 },
      { name: "Jesper Lindstrøm", position: "MID", ...R(68, 74, 40), rarity: "RARE", rating: 6.9 },
      { name: "Tim Iroegbunam", position: "MID", ...R(55, 72, 55), rarity: "BASE", rating: 6.7 },
      { name: "Nathan Patterson", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Beto", position: "FWD", ...R(74, 60, 22), rarity: "RARE", rating: 6.7 },
    ],
  },
  {
    name: "Leeds United", shortName: "LEE", country: "Inglaterra",
    colors: { primary: "#ffffff", secondary: "#005dbb", accent: "#ffcc00" },
    players: [
      { name: "Karl Darlow", position: "GK", ...R(25, 56, 80), rarity: "BASE", rating: 6.7 },
      { name: "Pascal Struijk", position: "DEF", ...R(45, 68, 82), rarity: "RARE", rating: 6.9 },
      { name: "Sam Byram", position: "DEF", ...R(45, 65, 78), rarity: "BASE", rating: 6.7 },
      { name: "Junior Firpo", position: "DEF", ...R(55, 68, 76), rarity: "BASE", rating: 6.7 },
      { name: "Crysencio Summerville", position: "FWD", ...R(78, 72, 28), rarity: "EPIC", goals: 7, assists: 5, rating: 7.1 },
      { name: "Ethan Ampadu", position: "MID", ...R(50, 76, 62), rarity: "RARE", rating: 6.9 },
      { name: "Ilia Gruev", position: "MID", ...R(50, 74, 55), rarity: "BASE", rating: 6.8 },
      { name: "Glen Kamara", position: "MID", ...R(55, 74, 55), rarity: "BASE", rating: 6.8 },
      { name: "Wilfried Gnonto", position: "FWD", ...R(76, 72, 25), rarity: "RARE", rating: 7.0 },
      { name: "Georginio Rutter", position: "FWD", ...R(76, 74, 28), rarity: "RARE", goals: 6, assists: 4, rating: 7.0 },
      { name: "Joel Piroe", position: "FWD", ...R(74, 70, 25), rarity: "RARE", goals: 5, assists: 3, rating: 6.9 },
      { name: "Jayden Bogle", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Max Wöber", position: "DEF", ...R(35, 62, 78), rarity: "BASE", rating: 6.7 },
      { name: "Patrick Bamford", position: "FWD", ...R(74, 65, 25), rarity: "RARE", rating: 6.8 },
      { name: "Dan James", position: "FWD", ...R(76, 68, 25), rarity: "RARE", rating: 6.9 },
      { name: "Ampadu", position: "MID", ...R(50, 74, 60), rarity: "BASE", rating: 6.7 },
    ],
  },
  {
    name: "Crystal Palace", shortName: "CRY", country: "Inglaterra",
    colors: { primary: "#005dbb", secondary: "#ffffff", accent: "#c8102e" },
    players: [
      { name: "Dean Henderson", position: "GK", ...R(28, 58, 86), rarity: "EPIC", rating: 7.1 },
      { name: "Marc Guéhi", position: "DEF", ...R(45, 72, 86), rarity: "EPIC", rating: 7.2 },
      { name: "Joachim Andersen", position: "DEF", ...R(40, 68, 84), rarity: "RARE", rating: 7.0 },
      { name: "Tyrick Mitchell", position: "DEF", ...R(52, 68, 80), rarity: "RARE", rating: 6.9 },
      { name: "Daniel Muñoz", position: "DEF", ...R(55, 68, 78), rarity: "RARE", rating: 6.9 },
      { name: "Jefferson Lerma", position: "MID", ...R(55, 74, 65), rarity: "RARE", rating: 7.0 },
      { name: "Adam Wharton", position: "MID", ...R(55, 78, 58), rarity: "RARE", rating: 7.0 },
      { name: "Eberechi Eze", position: "MID", ...R(82, 84, 40), rarity: "EPIC", goals: 7, assists: 5, rating: 7.3 },
      { name: "Michael Olise", position: "MID", ...R(80, 82, 35), rarity: "EPIC", goals: 5, assists: 6, rating: 7.2 },
      { name: "Jean-Philippe Mateta", position: "FWD", ...R(80, 68, 28), rarity: "RARE", goals: 8, assists: 3, rating: 7.1 },
      { name: "Odsonne Edouard", position: "FWD", ...R(76, 68, 25), rarity: "RARE", rating: 6.9 },
      { name: "Will Hughes", position: "MID", ...R(55, 74, 50), rarity: "BASE", rating: 6.8 },
      { name: "Cheick Doucouré", position: "MID", ...R(50, 72, 65), rarity: "RARE", rating: 6.9 },
      { name: "Joel Ward", position: "DEF", ...R(40, 62, 76), rarity: "BASE", rating: 6.7 },
      { name: "Jordan Ayew", position: "FWD", ...R(72, 68, 30), rarity: "RARE", rating: 6.9 },
      { name: "Chris Richards", position: "DEF", ...R(35, 62, 78), rarity: "RARE", rating: 6.8 },
    ],
  },
  {
    name: "Nottingham Forest", shortName: "NFO", country: "Inglaterra",
    colors: { primary: "#c8102e", secondary: "#ffffff", accent: "#000000" },
    players: [
      { name: "Matz Sels", position: "GK", ...R(28, 58, 82), rarity: "RARE", rating: 6.9 },
      { name: "Murillo", position: "DEF", ...R(45, 68, 84), rarity: "EPIC", rating: 7.1 },
      { name: "Neco Williams", position: "DEF", ...R(55, 68, 78), rarity: "RARE", rating: 6.8 },
      { name: "Ola Aina", position: "DEF", ...R(50, 68, 78), rarity: "RARE", rating: 6.9 },
      { name: "Harry Toffolo", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Ibrahim Sangaré", position: "MID", ...R(55, 78, 65), rarity: "RARE", rating: 7.0 },
      { name: "Morgan Gibbs-White", position: "MID", ...R(82, 82, 42), rarity: "GOLDEN", goals: 15, assists: 6, rating: 7.5 },
      { name: "Ryan Yates", position: "MID", ...R(55, 72, 58), rarity: "BASE", rating: 6.8 },
      { name: "Anthony Elanga", position: "FWD", ...R(80, 72, 28), rarity: "RARE", goals: 5, assists: 4, rating: 7.0 },
      { name: "Taiwo Awoniyi", position: "FWD", ...R(78, 65, 25), rarity: "RARE", goals: 6, assists: 3, rating: 6.9 },
      { name: "Chris Wood", position: "FWD", ...R(76, 62, 25), rarity: "RARE", goals: 5, assists: 2, rating: 6.9 },
      { name: "Callum Hudson-Odoi", position: "FWD", ...R(76, 74, 28), rarity: "RARE", rating: 7.0 },
      { name: "Danilo", position: "MID", ...R(58, 74, 50), rarity: "RARE", rating: 6.9 },
      { name: "Nicolas Dominguez", position: "MID", ...R(60, 74, 52), rarity: "RARE", rating: 6.9 },
      { name: "Andrew Omobamidele", position: "DEF", ...R(35, 62, 78), rarity: "BASE", rating: 6.7 },
      { name: "Taiwo Avoniyi", position: "FWD", ...R(78, 62, 25), rarity: "RARE", rating: 6.9 },
    ],
  },
  {
    name: "Tottenham Hotspur", shortName: "TOT", country: "Inglaterra",
    colors: { primary: "#ffffff", secondary: "#005dbb", accent: "#000000" },
    players: [
      { name: "Guglielmo Vicario", position: "GK", ...R(28, 60, 86), rarity: "EPIC", rating: 7.1 },
      { name: "Cristian Romero", position: "DEF", ...R(50, 68, 86), rarity: "EPIC", rating: 7.2 },
      { name: "Micky van de Ven", position: "DEF", ...R(45, 70, 84), rarity: "EPIC", rating: 7.2 },
      { name: "Pedro Porro", position: "DEF", ...R(62, 76, 76), rarity: "EPIC", rating: 7.1 },
      { name: "Destiny Udogie", position: "DEF", ...R(58, 72, 78), rarity: "EPIC", rating: 7.1 },
      { name: "James Maddison", position: "MID", ...R(82, 86, 40), rarity: "EPIC", goals: 6, assists: 6, rating: 7.3 },
      { name: "Yves Bissouma", position: "MID", ...R(55, 78, 65), rarity: "RARE", rating: 7.0 },
      { name: "Pape Matar Sarr", position: "MID", ...R(62, 78, 55), rarity: "EPIC", rating: 7.1 },
      { name: "Dejan Kulusevski", position: "MID", ...R(78, 80, 42), rarity: "EPIC", rating: 7.2 },
      { name: "Heung-min Son", position: "FWD", ...R(88, 78, 30), rarity: "LEGENDARY", goals: 8, assists: 6, rating: 7.3 },
      { name: "Richarlison", position: "FWD", ...R(80, 68, 30), rarity: "RARE", goals: 5, assists: 3, rating: 7.0 },
      { name: "Brennan Johnson", position: "FWD", ...R(76, 72, 28), rarity: "RARE", rating: 6.9 },
      { name: "Rodrigo Bentancur", position: "MID", ...R(58, 78, 58), rarity: "RARE", rating: 7.0 },
      { name: "Radu Drăgușin", position: "DEF", ...R(40, 62, 80), rarity: "RARE", rating: 6.9 },
      { name: "Timo Werner", position: "FWD", ...R(76, 70, 25), rarity: "RARE", rating: 6.8 },
      { name: "Thomas Frank", position: "MID", ...R(55, 72, 50), rarity: "RARE", rating: 6.8 },
    ],
  },
  {
    name: "West Ham United", shortName: "WHU", country: "Inglaterra",
    colors: { primary: "#6d2077", secondary: "#ffffff", accent: "#6cabdd" },
    players: [
      { name: "Alphonse Areola", position: "GK", ...R(28, 58, 84), rarity: "RARE", rating: 7.0 },
      { name: "Kurt Zouma", position: "DEF", ...R(40, 65, 84), rarity: "RARE", rating: 7.0 },
      { name: "Nayef Aguerd", position: "DEF", ...R(40, 68, 82), rarity: "RARE", rating: 7.0 },
      { name: "Emerson Palmieri", position: "DEF", ...R(55, 72, 78), rarity: "RARE", rating: 6.9 },
      { name: "Vladimír Coufal", position: "DEF", ...R(50, 68, 78), rarity: "BASE", rating: 6.8 },
      { name: "Lucas Paquetá", position: "MID", ...R(78, 84, 45), rarity: "EPIC", rating: 7.2 },
      { name: "Edson Álvarez", position: "MID", ...R(50, 74, 70), rarity: "RARE", rating: 7.0 },
      { name: "James Ward-Prowse", position: "MID", ...R(72, 82, 55), rarity: "EPIC", goals: 5, assists: 6, rating: 7.2 },
      { name: "Jarrod Bowen", position: "FWD", ...R(84, 76, 35), rarity: "EPIC", goals: 8, assists: 5, rating: 7.3 },
      { name: "Mohammed Kudus", position: "MID", ...R(82, 78, 38), rarity: "EPIC", goals: 6, assists: 5, rating: 7.2 },
      { name: "Niklas Füllkrug", position: "FWD", ...R(80, 62, 25), rarity: "RARE", goals: 5, assists: 3, rating: 6.9 },
      { name: "Crysencio Summerville", position: "FWD", ...R(76, 72, 25), rarity: "RARE", rating: 7.0 },
      { name: "Tomáš Souček", position: "MID", ...R(62, 72, 62), rarity: "RARE", rating: 7.0 },
      { name: "Aaron Wan-Bissaka", position: "DEF", ...R(45, 62, 80), rarity: "RARE", rating: 6.9 },
      { name: "Maxwel Cornet", position: "FWD", ...R(72, 65, 25), rarity: "BASE", rating: 6.7 },
      { name: "Danny Ings", position: "FWD", ...R(76, 65, 25), rarity: "RARE", rating: 6.8 },
    ],
  },
  {
    name: "Burnley", shortName: "BUR", country: "Inglaterra",
    colors: { primary: "#6d2077", secondary: "#ffffff", accent: "#00e5ff" },
    players: [
      { name: "James Trafford", position: "GK", ...R(28, 58, 82), rarity: "RARE", rating: 6.9 },
      { name: "Dara O'Shea", position: "DEF", ...R(40, 62, 80), rarity: "BASE", rating: 6.8 },
      { name: "Jordan Beyer", position: "DEF", ...R(35, 62, 78), rarity: "BASE", rating: 6.7 },
      { name: "Charlie Taylor", position: "DEF", ...R(45, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Vitinho", position: "DEF", ...R(50, 65, 76), rarity: "BASE", rating: 6.7 },
      { name: "Josh Cullen", position: "MID", ...R(50, 72, 55), rarity: "BASE", rating: 6.7 },
      { name: "Sander Berge", position: "MID", ...R(55, 76, 60), rarity: "RARE", rating: 6.9 },
      { name: "Josh Brownhill", position: "MID", ...R(55, 74, 55), rarity: "RARE", rating: 6.8 },
      { name: "Lyle Foster", position: "FWD", ...R(74, 65, 25), rarity: "RARE", goals: 5, assists: 2, rating: 6.8 },
      { name: "Zeki Amdouni", position: "FWD", ...R(72, 68, 25), rarity: "RARE", rating: 6.8 },
      { name: "Jay Rodriguez", position: "FWD", ...R(72, 65, 25), rarity: "BASE", rating: 6.7 },
      { name: "Anass Zaroury", position: "FWD", ...R(72, 68, 25), rarity: "RARE", rating: 6.8 },
      { name: "Benson Manuel", position: "FWD", ...R(70, 68, 22), rarity: "BASE", rating: 6.7 },
      { name: "Connor Roberts", position: "DEF", ...R(48, 65, 76), rarity: "BASE", rating: 6.6 },
      { name: "Hannibal Mejbri", position: "MID", ...R(58, 72, 42), rarity: "RARE", rating: 6.7 },
      { name: "Luca Koleosho", position: "FWD", ...R(72, 68, 22), rarity: "RARE", rating: 6.8 },
    ],
  },
  {
    name: "Wolverhampton Wanderers", shortName: "WOL", country: "Inglaterra",
    colors: { primary: "#ffcc00", secondary: "#000000", accent: "#c8102e" },
    players: [
      { name: "José Sá", position: "GK", ...R(28, 58, 82), rarity: "RARE", rating: 6.9 },
      { name: "Max Kilman", position: "DEF", ...R(40, 65, 82), rarity: "RARE", rating: 6.9 },
      { name: "Craig Dawson", position: "DEF", ...R(35, 62, 80), rarity: "BASE", rating: 6.8 },
      { name: "Rayan Aït-Nouri", position: "DEF", ...R(58, 72, 76), rarity: "RARE", rating: 6.9 },
      { name: "Nélson Semedo", position: "DEF", ...R(52, 68, 78), rarity: "RARE", rating: 6.8 },
      { name: "João Gomes", position: "MID", ...R(55, 76, 62), rarity: "RARE", rating: 7.0 },
      { name: "Mario Lemina", position: "MID", ...R(58, 76, 60), rarity: "RARE", rating: 7.0 },
      { name: "Jean-Ricner Bellegarde", position: "MID", ...R(65, 72, 45), rarity: "RARE", rating: 6.9 },
      { name: "Matheus Cunha", position: "FWD", ...R(80, 76, 30), rarity: "EPIC", goals: 5, assists: 4, rating: 7.1 },
      { name: "Hwang Hee-chan", position: "FWD", ...R(78, 70, 28), rarity: "RARE", goals: 4, assists: 3, rating: 6.9 },
      { name: "Pablo Sarabia", position: "MID", ...R(72, 76, 35), rarity: "RARE", rating: 7.0 },
      { name: "Cunha", position: "FWD", ...R(78, 74, 28), rarity: "RARE", rating: 7.0 },
      { name: "Tommy Doyle", position: "MID", ...R(55, 74, 50), rarity: "BASE", rating: 6.7 },
      { name: "Santiago Bueno", position: "DEF", ...R(35, 60, 78), rarity: "BASE", rating: 6.7 },
      { name: "Hugo Bueno", position: "DEF", ...R(50, 68, 76), rarity: "BASE", rating: 6.7 },
      { name: "Fabio Silva", position: "FWD", ...R(72, 65, 22), rarity: "RARE", rating: 6.7 },
    ],
  },
];
